#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BASE")]
public partial class BaseDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertBRM_SQL_LIST(BRM_SQL_LIST instance);
  partial void UpdateBRM_SQL_LIST(BRM_SQL_LIST instance);
  partial void DeleteBRM_SQL_LIST(BRM_SQL_LIST instance);
  partial void InsertBRM_WF_Audit(BRM_WF_Audit instance);
  partial void UpdateBRM_WF_Audit(BRM_WF_Audit instance);
  partial void DeleteBRM_WF_Audit(BRM_WF_Audit instance);
  partial void InsertBRM_WF_DefineDetail(BRM_WF_DefineDetail instance);
  partial void UpdateBRM_WF_DefineDetail(BRM_WF_DefineDetail instance);
  partial void DeleteBRM_WF_DefineDetail(BRM_WF_DefineDetail instance);
  partial void InsertBRM_WF_Define(BRM_WF_Define instance);
  partial void UpdateBRM_WF_Define(BRM_WF_Define instance);
  partial void DeleteBRM_WF_Define(BRM_WF_Define instance);
  partial void InsertEPS_Attach_List(EPS_Attach_List instance);
  partial void UpdateEPS_Attach_List(EPS_Attach_List instance);
  partial void DeleteEPS_Attach_List(EPS_Attach_List instance);
  partial void InsertBRM_WF_Authorization(BRM_WF_Authorization instance);
  partial void UpdateBRM_WF_Authorization(BRM_WF_Authorization instance);
  partial void DeleteBRM_WF_Authorization(BRM_WF_Authorization instance);
  partial void InsertSystem_Manager(System_Manager instance);
  partial void UpdateSystem_Manager(System_Manager instance);
  partial void DeleteSystem_Manager(System_Manager instance);
  #endregion
	
	public BaseDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BASEConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<BRM_SQL_LIST> BRM_SQL_LIST
	{
		get
		{
			return this.GetTable<BRM_SQL_LIST>();
		}
	}
	
	public System.Data.Linq.Table<BRM_WF_Audit> BRM_WF_Audit
	{
		get
		{
			return this.GetTable<BRM_WF_Audit>();
		}
	}
	
	public System.Data.Linq.Table<BRM_WF_DefineDetail> BRM_WF_DefineDetail
	{
		get
		{
			return this.GetTable<BRM_WF_DefineDetail>();
		}
	}
	
	public System.Data.Linq.Table<V_EPS_FormList> V_EPS_FormList
	{
		get
		{
			return this.GetTable<V_EPS_FormList>();
		}
	}
	
	public System.Data.Linq.Table<BRM_WF_Define> BRM_WF_Define
	{
		get
		{
			return this.GetTable<BRM_WF_Define>();
		}
	}
	
	public System.Data.Linq.Table<EPS_Attach_List> EPS_Attach_List
	{
		get
		{
			return this.GetTable<EPS_Attach_List>();
		}
	}
	
	public System.Data.Linq.Table<System_Index> System_Index
	{
		get
		{
			return this.GetTable<System_Index>();
		}
	}
	
	public System.Data.Linq.Table<BRM_USER_INFO> BRM_USER_INFO
	{
		get
		{
			return this.GetTable<BRM_USER_INFO>();
		}
	}
	
	public System.Data.Linq.Table<BRM_WF_Authorization> BRM_WF_Authorization
	{
		get
		{
			return this.GetTable<BRM_WF_Authorization>();
		}
	}
	
	public System.Data.Linq.Table<System_Manager> System_Manager
	{
		get
		{
			return this.GetTable<System_Manager>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_SQL_LIST")]
public partial class BRM_SQL_LIST : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sqlid;
	
	private string _sqlName;
	
	private string _sqlCheck;
	
	private string _sqlText;
	
	private string _sqlElse;
	
	private string _sqlAfter;
	
	private string _pageSize;
	
	private string _sqlWhere;
	
	private string _sqlGroupby;
	
	private string _sqlOrderby;
	
	private string _sqlComment;
	
	private string _Creator;
	
	private System.DateTime _updateTime;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsqlidChanging(int value);
    partial void OnsqlidChanged();
    partial void OnsqlNameChanging(string value);
    partial void OnsqlNameChanged();
    partial void OnsqlCheckChanging(string value);
    partial void OnsqlCheckChanged();
    partial void OnsqlTextChanging(string value);
    partial void OnsqlTextChanged();
    partial void OnsqlElseChanging(string value);
    partial void OnsqlElseChanged();
    partial void OnsqlAfterChanging(string value);
    partial void OnsqlAfterChanged();
    partial void OnpageSizeChanging(string value);
    partial void OnpageSizeChanged();
    partial void OnsqlWhereChanging(string value);
    partial void OnsqlWhereChanged();
    partial void OnsqlGroupbyChanging(string value);
    partial void OnsqlGroupbyChanged();
    partial void OnsqlOrderbyChanging(string value);
    partial void OnsqlOrderbyChanged();
    partial void OnsqlCommentChanging(string value);
    partial void OnsqlCommentChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnupdateTimeChanging(System.DateTime value);
    partial void OnupdateTimeChanged();
    #endregion
	
	public BRM_SQL_LIST()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sqlid
	{
		get
		{
			return this._sqlid;
		}
		set
		{
			if ((this._sqlid != value))
			{
				this.OnsqlidChanging(value);
				this.SendPropertyChanging();
				this._sqlid = value;
				this.SendPropertyChanged("sqlid");
				this.OnsqlidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string sqlName
	{
		get
		{
			return this._sqlName;
		}
		set
		{
			if ((this._sqlName != value))
			{
				this.OnsqlNameChanging(value);
				this.SendPropertyChanging();
				this._sqlName = value;
				this.SendPropertyChanged("sqlName");
				this.OnsqlNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlCheck", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
	public string sqlCheck
	{
		get
		{
			return this._sqlCheck;
		}
		set
		{
			if ((this._sqlCheck != value))
			{
				this.OnsqlCheckChanging(value);
				this.SendPropertyChanging();
				this._sqlCheck = value;
				this.SendPropertyChanged("sqlCheck");
				this.OnsqlCheckChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlText", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
	public string sqlText
	{
		get
		{
			return this._sqlText;
		}
		set
		{
			if ((this._sqlText != value))
			{
				this.OnsqlTextChanging(value);
				this.SendPropertyChanging();
				this._sqlText = value;
				this.SendPropertyChanged("sqlText");
				this.OnsqlTextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlElse", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
	public string sqlElse
	{
		get
		{
			return this._sqlElse;
		}
		set
		{
			if ((this._sqlElse != value))
			{
				this.OnsqlElseChanging(value);
				this.SendPropertyChanging();
				this._sqlElse = value;
				this.SendPropertyChanged("sqlElse");
				this.OnsqlElseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlAfter", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
	public string sqlAfter
	{
		get
		{
			return this._sqlAfter;
		}
		set
		{
			if ((this._sqlAfter != value))
			{
				this.OnsqlAfterChanging(value);
				this.SendPropertyChanging();
				this._sqlAfter = value;
				this.SendPropertyChanged("sqlAfter");
				this.OnsqlAfterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageSize", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string pageSize
	{
		get
		{
			return this._pageSize;
		}
		set
		{
			if ((this._pageSize != value))
			{
				this.OnpageSizeChanging(value);
				this.SendPropertyChanging();
				this._pageSize = value;
				this.SendPropertyChanged("pageSize");
				this.OnpageSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlWhere", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string sqlWhere
	{
		get
		{
			return this._sqlWhere;
		}
		set
		{
			if ((this._sqlWhere != value))
			{
				this.OnsqlWhereChanging(value);
				this.SendPropertyChanging();
				this._sqlWhere = value;
				this.SendPropertyChanged("sqlWhere");
				this.OnsqlWhereChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlGroupby", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string sqlGroupby
	{
		get
		{
			return this._sqlGroupby;
		}
		set
		{
			if ((this._sqlGroupby != value))
			{
				this.OnsqlGroupbyChanging(value);
				this.SendPropertyChanging();
				this._sqlGroupby = value;
				this.SendPropertyChanged("sqlGroupby");
				this.OnsqlGroupbyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlOrderby", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string sqlOrderby
	{
		get
		{
			return this._sqlOrderby;
		}
		set
		{
			if ((this._sqlOrderby != value))
			{
				this.OnsqlOrderbyChanging(value);
				this.SendPropertyChanging();
				this._sqlOrderby = value;
				this.SendPropertyChanged("sqlOrderby");
				this.OnsqlOrderbyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlComment", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string sqlComment
	{
		get
		{
			return this._sqlComment;
		}
		set
		{
			if ((this._sqlComment != value))
			{
				this.OnsqlCommentChanging(value);
				this.SendPropertyChanging();
				this._sqlComment = value;
				this.SendPropertyChanged("sqlComment");
				this.OnsqlCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateTime", DbType="DateTime NOT NULL")]
	public System.DateTime updateTime
	{
		get
		{
			return this._updateTime;
		}
		set
		{
			if ((this._updateTime != value))
			{
				this.OnupdateTimeChanging(value);
				this.SendPropertyChanging();
				this._updateTime = value;
				this.SendPropertyChanged("updateTime");
				this.OnupdateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_WF_Audit")]
public partial class BRM_WF_Audit : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AuditID;
	
	private int _WFID;
	
	private int _NodeSeq;
	
	private int _FormID;
	
	private string _FormTable;
	
	private string _FormColumn;
	
	private string _FormType;
	
	private string _NodeName;
	
	private string _OwnerList;
	
	private string _OwnerName;
	
	private string _TheOwner;
	
	private string _TheName;
	
	private string _Action;
	
	private System.Nullable<int> _NextSeq;
	
	private string _NextOwnerList;
	
	private string _LastAction;
	
	private string _LastOwner;
	
	private System.Nullable<int> _IsAgent;
	
	private System.Nullable<int> _IsCounter;
	
	private string _Comment;
	
	private string _SetSelectNode;
	
	private string _SetSelectList;
	
	private string _NotifyList;
	
	private string _NotifyMsg;
	
	private System.DateTime _CreateTime;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
	private System.Nullable<char> _WFClosed;
	
	private string _CA_NO;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuditIDChanging(int value);
    partial void OnAuditIDChanged();
    partial void OnWFIDChanging(int value);
    partial void OnWFIDChanged();
    partial void OnNodeSeqChanging(int value);
    partial void OnNodeSeqChanged();
    partial void OnFormIDChanging(int value);
    partial void OnFormIDChanged();
    partial void OnFormTableChanging(string value);
    partial void OnFormTableChanged();
    partial void OnFormColumnChanging(string value);
    partial void OnFormColumnChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnOwnerListChanging(string value);
    partial void OnOwnerListChanged();
    partial void OnOwnerNameChanging(string value);
    partial void OnOwnerNameChanged();
    partial void OnTheOwnerChanging(string value);
    partial void OnTheOwnerChanged();
    partial void OnTheNameChanging(string value);
    partial void OnTheNameChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnNextSeqChanging(System.Nullable<int> value);
    partial void OnNextSeqChanged();
    partial void OnNextOwnerListChanging(string value);
    partial void OnNextOwnerListChanged();
    partial void OnLastActionChanging(string value);
    partial void OnLastActionChanged();
    partial void OnLastOwnerChanging(string value);
    partial void OnLastOwnerChanged();
    partial void OnIsAgentChanging(System.Nullable<int> value);
    partial void OnIsAgentChanged();
    partial void OnIsCounterChanging(System.Nullable<int> value);
    partial void OnIsCounterChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnSetSelectNodeChanging(string value);
    partial void OnSetSelectNodeChanged();
    partial void OnSetSelectListChanging(string value);
    partial void OnSetSelectListChanged();
    partial void OnNotifyListChanging(string value);
    partial void OnNotifyListChanged();
    partial void OnNotifyMsgChanging(string value);
    partial void OnNotifyMsgChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnWFClosedChanging(System.Nullable<char> value);
    partial void OnWFClosedChanged();
    partial void OnCA_NOChanging(string value);
    partial void OnCA_NOChanged();
    #endregion
	
	public BRM_WF_Audit()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AuditID
	{
		get
		{
			return this._AuditID;
		}
		set
		{
			if ((this._AuditID != value))
			{
				this.OnAuditIDChanging(value);
				this.SendPropertyChanging();
				this._AuditID = value;
				this.SendPropertyChanged("AuditID");
				this.OnAuditIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFID", DbType="Int NOT NULL")]
	public int WFID
	{
		get
		{
			return this._WFID;
		}
		set
		{
			if ((this._WFID != value))
			{
				this.OnWFIDChanging(value);
				this.SendPropertyChanging();
				this._WFID = value;
				this.SendPropertyChanged("WFID");
				this.OnWFIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int NOT NULL")]
	public int NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this.OnNodeSeqChanging(value);
				this.SendPropertyChanging();
				this._NodeSeq = value;
				this.SendPropertyChanged("NodeSeq");
				this.OnNodeSeqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int NOT NULL")]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this.OnFormIDChanging(value);
				this.SendPropertyChanging();
				this._FormID = value;
				this.SendPropertyChanged("FormID");
				this.OnFormIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTable", DbType="VarChar(50)")]
	public string FormTable
	{
		get
		{
			return this._FormTable;
		}
		set
		{
			if ((this._FormTable != value))
			{
				this.OnFormTableChanging(value);
				this.SendPropertyChanging();
				this._FormTable = value;
				this.SendPropertyChanged("FormTable");
				this.OnFormTableChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormColumn", DbType="VarChar(50)")]
	public string FormColumn
	{
		get
		{
			return this._FormColumn;
		}
		set
		{
			if ((this._FormColumn != value))
			{
				this.OnFormColumnChanging(value);
				this.SendPropertyChanging();
				this._FormColumn = value;
				this.SendPropertyChanged("FormColumn");
				this.OnFormColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(50)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this.OnFormTypeChanging(value);
				this.SendPropertyChanging();
				this._FormType = value;
				this.SendPropertyChanged("FormType");
				this.OnFormTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string NodeName
	{
		get
		{
			return this._NodeName;
		}
		set
		{
			if ((this._NodeName != value))
			{
				this.OnNodeNameChanging(value);
				this.SendPropertyChanging();
				this._NodeName = value;
				this.SendPropertyChanged("NodeName");
				this.OnNodeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerList", DbType="VarChar(100)")]
	public string OwnerList
	{
		get
		{
			return this._OwnerList;
		}
		set
		{
			if ((this._OwnerList != value))
			{
				this.OnOwnerListChanging(value);
				this.SendPropertyChanging();
				this._OwnerList = value;
				this.SendPropertyChanged("OwnerList");
				this.OnOwnerListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerName", DbType="NVarChar(50)")]
	public string OwnerName
	{
		get
		{
			return this._OwnerName;
		}
		set
		{
			if ((this._OwnerName != value))
			{
				this.OnOwnerNameChanging(value);
				this.SendPropertyChanging();
				this._OwnerName = value;
				this.SendPropertyChanged("OwnerName");
				this.OnOwnerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOwner", DbType="VarChar(50)")]
	public string TheOwner
	{
		get
		{
			return this._TheOwner;
		}
		set
		{
			if ((this._TheOwner != value))
			{
				this.OnTheOwnerChanging(value);
				this.SendPropertyChanging();
				this._TheOwner = value;
				this.SendPropertyChanged("TheOwner");
				this.OnTheOwnerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheName", DbType="NVarChar(50)")]
	public string TheName
	{
		get
		{
			return this._TheName;
		}
		set
		{
			if ((this._TheName != value))
			{
				this.OnTheNameChanging(value);
				this.SendPropertyChanging();
				this._TheName = value;
				this.SendPropertyChanged("TheName");
				this.OnTheNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50)")]
	public string Action
	{
		get
		{
			return this._Action;
		}
		set
		{
			if ((this._Action != value))
			{
				this.OnActionChanging(value);
				this.SendPropertyChanging();
				this._Action = value;
				this.SendPropertyChanged("Action");
				this.OnActionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeq", DbType="Int")]
	public System.Nullable<int> NextSeq
	{
		get
		{
			return this._NextSeq;
		}
		set
		{
			if ((this._NextSeq != value))
			{
				this.OnNextSeqChanging(value);
				this.SendPropertyChanging();
				this._NextSeq = value;
				this.SendPropertyChanged("NextSeq");
				this.OnNextSeqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextOwnerList", DbType="VarChar(200)")]
	public string NextOwnerList
	{
		get
		{
			return this._NextOwnerList;
		}
		set
		{
			if ((this._NextOwnerList != value))
			{
				this.OnNextOwnerListChanging(value);
				this.SendPropertyChanging();
				this._NextOwnerList = value;
				this.SendPropertyChanged("NextOwnerList");
				this.OnNextOwnerListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAction", DbType="VarChar(50)")]
	public string LastAction
	{
		get
		{
			return this._LastAction;
		}
		set
		{
			if ((this._LastAction != value))
			{
				this.OnLastActionChanging(value);
				this.SendPropertyChanging();
				this._LastAction = value;
				this.SendPropertyChanged("LastAction");
				this.OnLastActionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastOwner", DbType="VarChar(50)")]
	public string LastOwner
	{
		get
		{
			return this._LastOwner;
		}
		set
		{
			if ((this._LastOwner != value))
			{
				this.OnLastOwnerChanging(value);
				this.SendPropertyChanging();
				this._LastOwner = value;
				this.SendPropertyChanged("LastOwner");
				this.OnLastOwnerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAgent", DbType="Int")]
	public System.Nullable<int> IsAgent
	{
		get
		{
			return this._IsAgent;
		}
		set
		{
			if ((this._IsAgent != value))
			{
				this.OnIsAgentChanging(value);
				this.SendPropertyChanging();
				this._IsAgent = value;
				this.SendPropertyChanged("IsAgent");
				this.OnIsAgentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCounter", DbType="Int")]
	public System.Nullable<int> IsCounter
	{
		get
		{
			return this._IsCounter;
		}
		set
		{
			if ((this._IsCounter != value))
			{
				this.OnIsCounterChanging(value);
				this.SendPropertyChanging();
				this._IsCounter = value;
				this.SendPropertyChanged("IsCounter");
				this.OnIsCounterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(500)")]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this.OnCommentChanging(value);
				this.SendPropertyChanging();
				this._Comment = value;
				this.SendPropertyChanged("Comment");
				this.OnCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetSelectNode", DbType="VarChar(50)")]
	public string SetSelectNode
	{
		get
		{
			return this._SetSelectNode;
		}
		set
		{
			if ((this._SetSelectNode != value))
			{
				this.OnSetSelectNodeChanging(value);
				this.SendPropertyChanging();
				this._SetSelectNode = value;
				this.SendPropertyChanged("SetSelectNode");
				this.OnSetSelectNodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetSelectList", DbType="VarChar(100)")]
	public string SetSelectList
	{
		get
		{
			return this._SetSelectList;
		}
		set
		{
			if ((this._SetSelectList != value))
			{
				this.OnSetSelectListChanging(value);
				this.SendPropertyChanging();
				this._SetSelectList = value;
				this.SendPropertyChanged("SetSelectList");
				this.OnSetSelectListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyList", DbType="VarChar(100)")]
	public string NotifyList
	{
		get
		{
			return this._NotifyList;
		}
		set
		{
			if ((this._NotifyList != value))
			{
				this.OnNotifyListChanging(value);
				this.SendPropertyChanging();
				this._NotifyList = value;
				this.SendPropertyChanged("NotifyList");
				this.OnNotifyListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyMsg", DbType="NVarChar(500)")]
	public string NotifyMsg
	{
		get
		{
			return this._NotifyMsg;
		}
		set
		{
			if ((this._NotifyMsg != value))
			{
				this.OnNotifyMsgChanging(value);
				this.SendPropertyChanging();
				this._NotifyMsg = value;
				this.SendPropertyChanged("NotifyMsg");
				this.OnNotifyMsgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
	public System.DateTime CreateTime
	{
		get
		{
			return this._CreateTime;
		}
		set
		{
			if ((this._CreateTime != value))
			{
				this.OnCreateTimeChanging(value);
				this.SendPropertyChanging();
				this._CreateTime = value;
				this.SendPropertyChanged("CreateTime");
				this.OnCreateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this.OnUpdateTimeChanging(value);
				this.SendPropertyChanging();
				this._UpdateTime = value;
				this.SendPropertyChanged("UpdateTime");
				this.OnUpdateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFClosed", DbType="Char(1)")]
	public System.Nullable<char> WFClosed
	{
		get
		{
			return this._WFClosed;
		}
		set
		{
			if ((this._WFClosed != value))
			{
				this.OnWFClosedChanging(value);
				this.SendPropertyChanging();
				this._WFClosed = value;
				this.SendPropertyChanged("WFClosed");
				this.OnWFClosedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_NO", DbType="VarChar(100)")]
	public string CA_NO
	{
		get
		{
			return this._CA_NO;
		}
		set
		{
			if ((this._CA_NO != value))
			{
				this.OnCA_NOChanging(value);
				this.SendPropertyChanging();
				this._CA_NO = value;
				this.SendPropertyChanged("CA_NO");
				this.OnCA_NOChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_WF_DefineDetail")]
public partial class BRM_WF_DefineDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _NodeID;
	
	private System.Nullable<int> _WFID;
	
	private string _WFName;
	
	private string _FormTable;
	
	private string _FormColumn;
	
	private string _FormType;
	
	private System.Nullable<int> _NodeSeq;
	
	private string _NodeName;
	
	private string _OwnerListBySQL;
	
	private string _OwnerListByManual;
	
	private string _NextSeqCondition;
	
	private System.Nullable<int> _NextSeq;
	
	private string _PreSelectNode;
	
	private string _PreSelectValid;
	
	private string _SelectList;
	
	private string _SelectListShow;
	
	private string _SetSelectList;
	
	private string _MailSubjectFor;
	
	private string _MailCommentFor;
	
	private System.Nullable<char> _MoreOwnerYN;
	
	private System.Nullable<char> _RepeatYN;
	
	private string _RepeatEndLevel;
	
	private string _CounterSignList;
	
	private string _ForwardTo;
	
	private string _NotifyList;
	
	private string _NotifyListSQL;
	
	private string _NotifyMSG;
	
	private System.Nullable<int> _TopID;
	
	private System.Nullable<char> _EndYN;
	
	private System.Nullable<int> _FormID;
	
	private string _StartCondition;
	
	private string _OwnerListByPosition;
	
	private string _NextSeqCondition2;
	
	private string _NextSeqCondition3;
	
	private string _EndCondition;
	
	private string _WF_ARID;
	
	private string _AgentName;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNodeIDChanging(int value);
    partial void OnNodeIDChanged();
    partial void OnWFIDChanging(System.Nullable<int> value);
    partial void OnWFIDChanged();
    partial void OnWFNameChanging(string value);
    partial void OnWFNameChanged();
    partial void OnFormTableChanging(string value);
    partial void OnFormTableChanged();
    partial void OnFormColumnChanging(string value);
    partial void OnFormColumnChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnNodeSeqChanging(System.Nullable<int> value);
    partial void OnNodeSeqChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnOwnerListBySQLChanging(string value);
    partial void OnOwnerListBySQLChanged();
    partial void OnOwnerListByManualChanging(string value);
    partial void OnOwnerListByManualChanged();
    partial void OnNextSeqConditionChanging(string value);
    partial void OnNextSeqConditionChanged();
    partial void OnNextSeqChanging(System.Nullable<int> value);
    partial void OnNextSeqChanged();
    partial void OnPreSelectNodeChanging(string value);
    partial void OnPreSelectNodeChanged();
    partial void OnPreSelectValidChanging(string value);
    partial void OnPreSelectValidChanged();
    partial void OnSelectListChanging(string value);
    partial void OnSelectListChanged();
    partial void OnSelectListShowChanging(string value);
    partial void OnSelectListShowChanged();
    partial void OnSetSelectListChanging(string value);
    partial void OnSetSelectListChanged();
    partial void OnMailSubjectForChanging(string value);
    partial void OnMailSubjectForChanged();
    partial void OnMailCommentForChanging(string value);
    partial void OnMailCommentForChanged();
    partial void OnMoreOwnerYNChanging(System.Nullable<char> value);
    partial void OnMoreOwnerYNChanged();
    partial void OnRepeatYNChanging(System.Nullable<char> value);
    partial void OnRepeatYNChanged();
    partial void OnRepeatEndLevelChanging(string value);
    partial void OnRepeatEndLevelChanged();
    partial void OnCounterSignListChanging(string value);
    partial void OnCounterSignListChanged();
    partial void OnForwardToChanging(string value);
    partial void OnForwardToChanged();
    partial void OnNotifyListChanging(string value);
    partial void OnNotifyListChanged();
    partial void OnNotifyListSQLChanging(string value);
    partial void OnNotifyListSQLChanged();
    partial void OnNotifyMSGChanging(string value);
    partial void OnNotifyMSGChanged();
    partial void OnTopIDChanging(System.Nullable<int> value);
    partial void OnTopIDChanged();
    partial void OnEndYNChanging(System.Nullable<char> value);
    partial void OnEndYNChanged();
    partial void OnFormIDChanging(System.Nullable<int> value);
    partial void OnFormIDChanged();
    partial void OnStartConditionChanging(string value);
    partial void OnStartConditionChanged();
    partial void OnOwnerListByPositionChanging(string value);
    partial void OnOwnerListByPositionChanged();
    partial void OnNextSeqCondition2Changing(string value);
    partial void OnNextSeqCondition2Changed();
    partial void OnNextSeqCondition3Changing(string value);
    partial void OnNextSeqCondition3Changed();
    partial void OnEndConditionChanging(string value);
    partial void OnEndConditionChanged();
    partial void OnWF_ARIDChanging(string value);
    partial void OnWF_ARIDChanged();
    partial void OnAgentNameChanging(string value);
    partial void OnAgentNameChanged();
    #endregion
	
	public BRM_WF_DefineDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int NodeID
	{
		get
		{
			return this._NodeID;
		}
		set
		{
			if ((this._NodeID != value))
			{
				this.OnNodeIDChanging(value);
				this.SendPropertyChanging();
				this._NodeID = value;
				this.SendPropertyChanged("NodeID");
				this.OnNodeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFID", DbType="Int")]
	public System.Nullable<int> WFID
	{
		get
		{
			return this._WFID;
		}
		set
		{
			if ((this._WFID != value))
			{
				this.OnWFIDChanging(value);
				this.SendPropertyChanging();
				this._WFID = value;
				this.SendPropertyChanged("WFID");
				this.OnWFIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFName", DbType="NVarChar(50)")]
	public string WFName
	{
		get
		{
			return this._WFName;
		}
		set
		{
			if ((this._WFName != value))
			{
				this.OnWFNameChanging(value);
				this.SendPropertyChanging();
				this._WFName = value;
				this.SendPropertyChanged("WFName");
				this.OnWFNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTable", DbType="VarChar(50)")]
	public string FormTable
	{
		get
		{
			return this._FormTable;
		}
		set
		{
			if ((this._FormTable != value))
			{
				this.OnFormTableChanging(value);
				this.SendPropertyChanging();
				this._FormTable = value;
				this.SendPropertyChanged("FormTable");
				this.OnFormTableChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormColumn", DbType="VarChar(50)")]
	public string FormColumn
	{
		get
		{
			return this._FormColumn;
		}
		set
		{
			if ((this._FormColumn != value))
			{
				this.OnFormColumnChanging(value);
				this.SendPropertyChanging();
				this._FormColumn = value;
				this.SendPropertyChanged("FormColumn");
				this.OnFormColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(50)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this.OnFormTypeChanging(value);
				this.SendPropertyChanging();
				this._FormType = value;
				this.SendPropertyChanged("FormType");
				this.OnFormTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int")]
	public System.Nullable<int> NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this.OnNodeSeqChanging(value);
				this.SendPropertyChanging();
				this._NodeSeq = value;
				this.SendPropertyChanged("NodeSeq");
				this.OnNodeSeqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="VarChar(50)")]
	public string NodeName
	{
		get
		{
			return this._NodeName;
		}
		set
		{
			if ((this._NodeName != value))
			{
				this.OnNodeNameChanging(value);
				this.SendPropertyChanging();
				this._NodeName = value;
				this.SendPropertyChanged("NodeName");
				this.OnNodeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerListBySQL", DbType="NVarChar(500)")]
	public string OwnerListBySQL
	{
		get
		{
			return this._OwnerListBySQL;
		}
		set
		{
			if ((this._OwnerListBySQL != value))
			{
				this.OnOwnerListBySQLChanging(value);
				this.SendPropertyChanging();
				this._OwnerListBySQL = value;
				this.SendPropertyChanged("OwnerListBySQL");
				this.OnOwnerListBySQLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerListByManual", DbType="VarChar(50)")]
	public string OwnerListByManual
	{
		get
		{
			return this._OwnerListByManual;
		}
		set
		{
			if ((this._OwnerListByManual != value))
			{
				this.OnOwnerListByManualChanging(value);
				this.SendPropertyChanging();
				this._OwnerListByManual = value;
				this.SendPropertyChanged("OwnerListByManual");
				this.OnOwnerListByManualChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeqCondition", DbType="NVarChar(2000)")]
	public string NextSeqCondition
	{
		get
		{
			return this._NextSeqCondition;
		}
		set
		{
			if ((this._NextSeqCondition != value))
			{
				this.OnNextSeqConditionChanging(value);
				this.SendPropertyChanging();
				this._NextSeqCondition = value;
				this.SendPropertyChanged("NextSeqCondition");
				this.OnNextSeqConditionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeq", DbType="Int")]
	public System.Nullable<int> NextSeq
	{
		get
		{
			return this._NextSeq;
		}
		set
		{
			if ((this._NextSeq != value))
			{
				this.OnNextSeqChanging(value);
				this.SendPropertyChanging();
				this._NextSeq = value;
				this.SendPropertyChanged("NextSeq");
				this.OnNextSeqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSelectNode", DbType="NVarChar(50)")]
	public string PreSelectNode
	{
		get
		{
			return this._PreSelectNode;
		}
		set
		{
			if ((this._PreSelectNode != value))
			{
				this.OnPreSelectNodeChanging(value);
				this.SendPropertyChanging();
				this._PreSelectNode = value;
				this.SendPropertyChanged("PreSelectNode");
				this.OnPreSelectNodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSelectValid", DbType="NVarChar(800)")]
	public string PreSelectValid
	{
		get
		{
			return this._PreSelectValid;
		}
		set
		{
			if ((this._PreSelectValid != value))
			{
				this.OnPreSelectValidChanging(value);
				this.SendPropertyChanging();
				this._PreSelectValid = value;
				this.SendPropertyChanged("PreSelectValid");
				this.OnPreSelectValidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectList", DbType="NVarChar(100)")]
	public string SelectList
	{
		get
		{
			return this._SelectList;
		}
		set
		{
			if ((this._SelectList != value))
			{
				this.OnSelectListChanging(value);
				this.SendPropertyChanging();
				this._SelectList = value;
				this.SendPropertyChanged("SelectList");
				this.OnSelectListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectListShow", DbType="NVarChar(100)")]
	public string SelectListShow
	{
		get
		{
			return this._SelectListShow;
		}
		set
		{
			if ((this._SelectListShow != value))
			{
				this.OnSelectListShowChanging(value);
				this.SendPropertyChanging();
				this._SelectListShow = value;
				this.SendPropertyChanged("SelectListShow");
				this.OnSelectListShowChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetSelectList", DbType="VarChar(50)")]
	public string SetSelectList
	{
		get
		{
			return this._SetSelectList;
		}
		set
		{
			if ((this._SetSelectList != value))
			{
				this.OnSetSelectListChanging(value);
				this.SendPropertyChanging();
				this._SetSelectList = value;
				this.SendPropertyChanged("SetSelectList");
				this.OnSetSelectListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailSubjectFor", DbType="VarChar(1000)")]
	public string MailSubjectFor
	{
		get
		{
			return this._MailSubjectFor;
		}
		set
		{
			if ((this._MailSubjectFor != value))
			{
				this.OnMailSubjectForChanging(value);
				this.SendPropertyChanging();
				this._MailSubjectFor = value;
				this.SendPropertyChanged("MailSubjectFor");
				this.OnMailSubjectForChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailCommentFor", DbType="VarChar(500)")]
	public string MailCommentFor
	{
		get
		{
			return this._MailCommentFor;
		}
		set
		{
			if ((this._MailCommentFor != value))
			{
				this.OnMailCommentForChanging(value);
				this.SendPropertyChanging();
				this._MailCommentFor = value;
				this.SendPropertyChanged("MailCommentFor");
				this.OnMailCommentForChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreOwnerYN", DbType="Char(1)")]
	public System.Nullable<char> MoreOwnerYN
	{
		get
		{
			return this._MoreOwnerYN;
		}
		set
		{
			if ((this._MoreOwnerYN != value))
			{
				this.OnMoreOwnerYNChanging(value);
				this.SendPropertyChanging();
				this._MoreOwnerYN = value;
				this.SendPropertyChanged("MoreOwnerYN");
				this.OnMoreOwnerYNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatYN", DbType="Char(1)")]
	public System.Nullable<char> RepeatYN
	{
		get
		{
			return this._RepeatYN;
		}
		set
		{
			if ((this._RepeatYN != value))
			{
				this.OnRepeatYNChanging(value);
				this.SendPropertyChanging();
				this._RepeatYN = value;
				this.SendPropertyChanged("RepeatYN");
				this.OnRepeatYNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatEndLevel", DbType="NVarChar(500)")]
	public string RepeatEndLevel
	{
		get
		{
			return this._RepeatEndLevel;
		}
		set
		{
			if ((this._RepeatEndLevel != value))
			{
				this.OnRepeatEndLevelChanging(value);
				this.SendPropertyChanging();
				this._RepeatEndLevel = value;
				this.SendPropertyChanged("RepeatEndLevel");
				this.OnRepeatEndLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterSignList", DbType="NVarChar(100)")]
	public string CounterSignList
	{
		get
		{
			return this._CounterSignList;
		}
		set
		{
			if ((this._CounterSignList != value))
			{
				this.OnCounterSignListChanging(value);
				this.SendPropertyChanging();
				this._CounterSignList = value;
				this.SendPropertyChanged("CounterSignList");
				this.OnCounterSignListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForwardTo", DbType="NVarChar(100)")]
	public string ForwardTo
	{
		get
		{
			return this._ForwardTo;
		}
		set
		{
			if ((this._ForwardTo != value))
			{
				this.OnForwardToChanging(value);
				this.SendPropertyChanging();
				this._ForwardTo = value;
				this.SendPropertyChanged("ForwardTo");
				this.OnForwardToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyList", DbType="NVarChar(100)")]
	public string NotifyList
	{
		get
		{
			return this._NotifyList;
		}
		set
		{
			if ((this._NotifyList != value))
			{
				this.OnNotifyListChanging(value);
				this.SendPropertyChanging();
				this._NotifyList = value;
				this.SendPropertyChanged("NotifyList");
				this.OnNotifyListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyListSQL", DbType="NVarChar(500)")]
	public string NotifyListSQL
	{
		get
		{
			return this._NotifyListSQL;
		}
		set
		{
			if ((this._NotifyListSQL != value))
			{
				this.OnNotifyListSQLChanging(value);
				this.SendPropertyChanging();
				this._NotifyListSQL = value;
				this.SendPropertyChanged("NotifyListSQL");
				this.OnNotifyListSQLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyMSG", DbType="NVarChar(100)")]
	public string NotifyMSG
	{
		get
		{
			return this._NotifyMSG;
		}
		set
		{
			if ((this._NotifyMSG != value))
			{
				this.OnNotifyMSGChanging(value);
				this.SendPropertyChanging();
				this._NotifyMSG = value;
				this.SendPropertyChanged("NotifyMSG");
				this.OnNotifyMSGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopID", DbType="Int")]
	public System.Nullable<int> TopID
	{
		get
		{
			return this._TopID;
		}
		set
		{
			if ((this._TopID != value))
			{
				this.OnTopIDChanging(value);
				this.SendPropertyChanging();
				this._TopID = value;
				this.SendPropertyChanged("TopID");
				this.OnTopIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndYN", DbType="Char(1)")]
	public System.Nullable<char> EndYN
	{
		get
		{
			return this._EndYN;
		}
		set
		{
			if ((this._EndYN != value))
			{
				this.OnEndYNChanging(value);
				this.SendPropertyChanging();
				this._EndYN = value;
				this.SendPropertyChanged("EndYN");
				this.OnEndYNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int")]
	public System.Nullable<int> FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this.OnFormIDChanging(value);
				this.SendPropertyChanging();
				this._FormID = value;
				this.SendPropertyChanged("FormID");
				this.OnFormIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCondition", DbType="NVarChar(500)")]
	public string StartCondition
	{
		get
		{
			return this._StartCondition;
		}
		set
		{
			if ((this._StartCondition != value))
			{
				this.OnStartConditionChanging(value);
				this.SendPropertyChanging();
				this._StartCondition = value;
				this.SendPropertyChanged("StartCondition");
				this.OnStartConditionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerListByPosition", DbType="NVarChar(50)")]
	public string OwnerListByPosition
	{
		get
		{
			return this._OwnerListByPosition;
		}
		set
		{
			if ((this._OwnerListByPosition != value))
			{
				this.OnOwnerListByPositionChanging(value);
				this.SendPropertyChanging();
				this._OwnerListByPosition = value;
				this.SendPropertyChanged("OwnerListByPosition");
				this.OnOwnerListByPositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeqCondition2", DbType="NVarChar(500)")]
	public string NextSeqCondition2
	{
		get
		{
			return this._NextSeqCondition2;
		}
		set
		{
			if ((this._NextSeqCondition2 != value))
			{
				this.OnNextSeqCondition2Changing(value);
				this.SendPropertyChanging();
				this._NextSeqCondition2 = value;
				this.SendPropertyChanged("NextSeqCondition2");
				this.OnNextSeqCondition2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeqCondition3", DbType="NVarChar(500)")]
	public string NextSeqCondition3
	{
		get
		{
			return this._NextSeqCondition3;
		}
		set
		{
			if ((this._NextSeqCondition3 != value))
			{
				this.OnNextSeqCondition3Changing(value);
				this.SendPropertyChanging();
				this._NextSeqCondition3 = value;
				this.SendPropertyChanged("NextSeqCondition3");
				this.OnNextSeqCondition3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndCondition", DbType="NVarChar(500)")]
	public string EndCondition
	{
		get
		{
			return this._EndCondition;
		}
		set
		{
			if ((this._EndCondition != value))
			{
				this.OnEndConditionChanging(value);
				this.SendPropertyChanging();
				this._EndCondition = value;
				this.SendPropertyChanged("EndCondition");
				this.OnEndConditionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WF_ARID", DbType="VarChar(50)")]
	public string WF_ARID
	{
		get
		{
			return this._WF_ARID;
		}
		set
		{
			if ((this._WF_ARID != value))
			{
				this.OnWF_ARIDChanging(value);
				this.SendPropertyChanging();
				this._WF_ARID = value;
				this.SendPropertyChanged("WF_ARID");
				this.OnWF_ARIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentName", DbType="VarChar(30)")]
	public string AgentName
	{
		get
		{
			return this._AgentName;
		}
		set
		{
			if ((this._AgentName != value))
			{
				this.OnAgentNameChanging(value);
				this.SendPropertyChanging();
				this._AgentName = value;
				this.SendPropertyChanged("AgentName");
				this.OnAgentNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EPS_FormList")]
public partial class V_EPS_FormList
{
	
	private int _FormID;
	
	private string _FormNo;
	
	private string _FormType;
	
	private string _FormTypeName;
	
	private string _Form_Status;
	
	private string _FormUrl;
	
	private string _ApplyManNo;
	
	private string _Register_Name;
	
	private string _AgentID;
	
	private System.Nullable<System.DateTime> _ApplyDate;
	
	private string _OwnerList;
	
	private System.Nullable<int> _NodeSeq;
	
	private string _NodeName;
	
	private string _ApplyDept;
	
	private string _TheOwner;
	
	private string _DeleteFlag;
	
	private string _LastAction;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
	private string _SysID;
	
	private string _TableID;
	
	private string _UrlLink;
	
	public V_EPS_FormList()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int NOT NULL")]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this._FormID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(80)")]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this._FormNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(30)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this._FormType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTypeName", DbType="VarChar(50)")]
	public string FormTypeName
	{
		get
		{
			return this._FormTypeName;
		}
		set
		{
			if ((this._FormTypeName != value))
			{
				this._FormTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form_Status", DbType="NVarChar(50)")]
	public string Form_Status
	{
		get
		{
			return this._Form_Status;
		}
		set
		{
			if ((this._Form_Status != value))
			{
				this._Form_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="VarChar(50)")]
	public string FormUrl
	{
		get
		{
			return this._FormUrl;
		}
		set
		{
			if ((this._FormUrl != value))
			{
				this._FormUrl = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyManNo", DbType="VarChar(10)")]
	public string ApplyManNo
	{
		get
		{
			return this._ApplyManNo;
		}
		set
		{
			if ((this._ApplyManNo != value))
			{
				this._ApplyManNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Register_Name", DbType="VarChar(41)")]
	public string Register_Name
	{
		get
		{
			return this._Register_Name;
		}
		set
		{
			if ((this._Register_Name != value))
			{
				this._Register_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="VarChar(30)")]
	public string AgentID
	{
		get
		{
			return this._AgentID;
		}
		set
		{
			if ((this._AgentID != value))
			{
				this._AgentID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ApplyDate
	{
		get
		{
			return this._ApplyDate;
		}
		set
		{
			if ((this._ApplyDate != value))
			{
				this._ApplyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerList", DbType="VarChar(100)")]
	public string OwnerList
	{
		get
		{
			return this._OwnerList;
		}
		set
		{
			if ((this._OwnerList != value))
			{
				this._OwnerList = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int")]
	public System.Nullable<int> NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this._NodeSeq = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(50)")]
	public string NodeName
	{
		get
		{
			return this._NodeName;
		}
		set
		{
			if ((this._NodeName != value))
			{
				this._NodeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDept", DbType="VarChar(50)")]
	public string ApplyDept
	{
		get
		{
			return this._ApplyDept;
		}
		set
		{
			if ((this._ApplyDept != value))
			{
				this._ApplyDept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOwner", DbType="VarChar(50)")]
	public string TheOwner
	{
		get
		{
			return this._TheOwner;
		}
		set
		{
			if ((this._TheOwner != value))
			{
				this._TheOwner = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAction", DbType="VarChar(50)")]
	public string LastAction
	{
		get
		{
			return this._LastAction;
		}
		set
		{
			if ((this._LastAction != value))
			{
				this._LastAction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this._UpdateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(10)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this._SysID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(10)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this._TableID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlLink", DbType="NVarChar(386)")]
	public string UrlLink
	{
		get
		{
			return this._UrlLink;
		}
		set
		{
			if ((this._UrlLink != value))
			{
				this._UrlLink = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_WF_Define")]
public partial class BRM_WF_Define : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _WFID;
	
	private string _WFName;
	
	private string _WFDesc;
	
	private string _FormTable;
	
	private string _FormColumn;
	
	private string _FormType;
	
	private string _MailList;
	
	private string _URL;
	
	private string _APURL;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateTime;
	
	private string _UpdateUser;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
	private string _Remark;
	
	private string _SysID;
	
	private string _TableID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWFIDChanging(int value);
    partial void OnWFIDChanged();
    partial void OnWFNameChanging(string value);
    partial void OnWFNameChanged();
    partial void OnWFDescChanging(string value);
    partial void OnWFDescChanged();
    partial void OnFormTableChanging(string value);
    partial void OnFormTableChanged();
    partial void OnFormColumnChanging(string value);
    partial void OnFormColumnChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnMailListChanging(string value);
    partial void OnMailListChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnAPURLChanging(string value);
    partial void OnAPURLChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnUpdateUserChanging(string value);
    partial void OnUpdateUserChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnSysIDChanging(string value);
    partial void OnSysIDChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    #endregion
	
	public BRM_WF_Define()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int WFID
	{
		get
		{
			return this._WFID;
		}
		set
		{
			if ((this._WFID != value))
			{
				this.OnWFIDChanging(value);
				this.SendPropertyChanging();
				this._WFID = value;
				this.SendPropertyChanged("WFID");
				this.OnWFIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFName", DbType="NVarChar(50)")]
	public string WFName
	{
		get
		{
			return this._WFName;
		}
		set
		{
			if ((this._WFName != value))
			{
				this.OnWFNameChanging(value);
				this.SendPropertyChanging();
				this._WFName = value;
				this.SendPropertyChanged("WFName");
				this.OnWFNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFDesc", DbType="NVarChar(50)")]
	public string WFDesc
	{
		get
		{
			return this._WFDesc;
		}
		set
		{
			if ((this._WFDesc != value))
			{
				this.OnWFDescChanging(value);
				this.SendPropertyChanging();
				this._WFDesc = value;
				this.SendPropertyChanged("WFDesc");
				this.OnWFDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTable", DbType="VarChar(50)")]
	public string FormTable
	{
		get
		{
			return this._FormTable;
		}
		set
		{
			if ((this._FormTable != value))
			{
				this.OnFormTableChanging(value);
				this.SendPropertyChanging();
				this._FormTable = value;
				this.SendPropertyChanged("FormTable");
				this.OnFormTableChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormColumn", DbType="VarChar(50)")]
	public string FormColumn
	{
		get
		{
			return this._FormColumn;
		}
		set
		{
			if ((this._FormColumn != value))
			{
				this.OnFormColumnChanging(value);
				this.SendPropertyChanging();
				this._FormColumn = value;
				this.SendPropertyChanged("FormColumn");
				this.OnFormColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(50)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this.OnFormTypeChanging(value);
				this.SendPropertyChanging();
				this._FormType = value;
				this.SendPropertyChanged("FormType");
				this.OnFormTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailList", DbType="NVarChar(50)")]
	public string MailList
	{
		get
		{
			return this._MailList;
		}
		set
		{
			if ((this._MailList != value))
			{
				this.OnMailListChanging(value);
				this.SendPropertyChanging();
				this._MailList = value;
				this.SendPropertyChanged("MailList");
				this.OnMailListChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(200)")]
	public string URL
	{
		get
		{
			return this._URL;
		}
		set
		{
			if ((this._URL != value))
			{
				this.OnURLChanging(value);
				this.SendPropertyChanging();
				this._URL = value;
				this.SendPropertyChanged("URL");
				this.OnURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APURL", DbType="VarChar(100)")]
	public string APURL
	{
		get
		{
			return this._APURL;
		}
		set
		{
			if ((this._APURL != value))
			{
				this.OnAPURLChanging(value);
				this.SendPropertyChanging();
				this._APURL = value;
				this.SendPropertyChanged("APURL");
				this.OnAPURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(50)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateTime
	{
		get
		{
			return this._CreateTime;
		}
		set
		{
			if ((this._CreateTime != value))
			{
				this.OnCreateTimeChanging(value);
				this.SendPropertyChanging();
				this._CreateTime = value;
				this.SendPropertyChanged("CreateTime");
				this.OnCreateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="VarChar(50)")]
	public string UpdateUser
	{
		get
		{
			return this._UpdateUser;
		}
		set
		{
			if ((this._UpdateUser != value))
			{
				this.OnUpdateUserChanging(value);
				this.SendPropertyChanging();
				this._UpdateUser = value;
				this.SendPropertyChanged("UpdateUser");
				this.OnUpdateUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this.OnUpdateTimeChanging(value);
				this.SendPropertyChanging();
				this._UpdateTime = value;
				this.SendPropertyChanged("UpdateTime");
				this.OnUpdateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(200)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(10)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this.OnSysIDChanging(value);
				this.SendPropertyChanging();
				this._SysID = value;
				this.SendPropertyChanged("SysID");
				this.OnSysIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(10)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this.OnTableIDChanging(value);
				this.SendPropertyChanging();
				this._TableID = value;
				this.SendPropertyChanged("TableID");
				this.OnTableIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EPS_Attach_List")]
public partial class EPS_Attach_List : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AttachID;
	
	private string _FormID;
	
	private string _SysID;
	
	private string _TableID;
	
	private string _Path;
	
	private string _FileName;
	
	private string _UploadUser;
	
	private System.Nullable<System.DateTime> _UploadTime;
	
	private string _DeleteFlag;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _ModifyMan;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	private string _Remark;
	
	private System.Data.Linq.Binary _purpose;
	
	private string _FieldName;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttachIDChanging(int value);
    partial void OnAttachIDChanged();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnSysIDChanging(string value);
    partial void OnSysIDChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnUploadUserChanging(string value);
    partial void OnUploadUserChanged();
    partial void OnUploadTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUploadTimeChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifyManChanging(string value);
    partial void OnModifyManChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnpurposeChanging(System.Data.Linq.Binary value);
    partial void OnpurposeChanged();
    partial void OnFieldNameChanging(string value);
    partial void OnFieldNameChanged();
    #endregion
	
	public EPS_Attach_List()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AttachID
	{
		get
		{
			return this._AttachID;
		}
		set
		{
			if ((this._AttachID != value))
			{
				this.OnAttachIDChanging(value);
				this.SendPropertyChanging();
				this._AttachID = value;
				this.SendPropertyChanged("AttachID");
				this.OnAttachIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this.OnFormIDChanging(value);
				this.SendPropertyChanging();
				this._FormID = value;
				this.SendPropertyChanged("FormID");
				this.OnFormIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(50)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this.OnSysIDChanging(value);
				this.SendPropertyChanging();
				this._SysID = value;
				this.SendPropertyChanged("SysID");
				this.OnSysIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(50)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this.OnTableIDChanging(value);
				this.SendPropertyChanging();
				this._TableID = value;
				this.SendPropertyChanged("TableID");
				this.OnTableIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(100)")]
	public string Path
	{
		get
		{
			return this._Path;
		}
		set
		{
			if ((this._Path != value))
			{
				this.OnPathChanging(value);
				this.SendPropertyChanging();
				this._Path = value;
				this.SendPropertyChanged("Path");
				this.OnPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadUser", DbType="VarChar(50)")]
	public string UploadUser
	{
		get
		{
			return this._UploadUser;
		}
		set
		{
			if ((this._UploadUser != value))
			{
				this.OnUploadUserChanging(value);
				this.SendPropertyChanging();
				this._UploadUser = value;
				this.SendPropertyChanged("UploadUser");
				this.OnUploadUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UploadTime
	{
		get
		{
			return this._UploadTime;
		}
		set
		{
			if ((this._UploadTime != value))
			{
				this.OnUploadTimeChanging(value);
				this.SendPropertyChanging();
				this._UploadTime = value;
				this.SendPropertyChanged("UploadTime");
				this.OnUploadTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(10)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(50)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyMan", DbType="VarChar(50)")]
	public string ModifyMan
	{
		get
		{
			return this._ModifyMan;
		}
		set
		{
			if ((this._ModifyMan != value))
			{
				this.OnModifyManChanging(value);
				this.SendPropertyChanging();
				this._ModifyMan = value;
				this.SendPropertyChanged("ModifyMan");
				this.OnModifyManChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(100)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purpose", DbType="VarBinary(100)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary purpose
	{
		get
		{
			return this._purpose;
		}
		set
		{
			if ((this._purpose != value))
			{
				this.OnpurposeChanging(value);
				this.SendPropertyChanging();
				this._purpose = value;
				this.SendPropertyChanged("purpose");
				this.OnpurposeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldName", DbType="VarChar(50)")]
	public string FieldName
	{
		get
		{
			return this._FieldName;
		}
		set
		{
			if ((this._FieldName != value))
			{
				this.OnFieldNameChanging(value);
				this.SendPropertyChanging();
				this._FieldName = value;
				this.SendPropertyChanged("FieldName");
				this.OnFieldNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.System_Index")]
public partial class System_Index
{
	
	private int _IndexID;
	
	private string _SysID;
	
	private string _TableID;
	
	private string _SysName;
	
	private string _TableName;
	
	private string _SystemType;
	
	private string _Route;
	
	private string _IsFlow;
	
	private string _WebFormName;
	
	private string _FormType;
	
	private string _CodeFormName;
	
	private string _URL;
	
	private string _APLinkURL;
	
	private string _AttachNameList;
	
	public System_Index()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int IndexID
	{
		get
		{
			return this._IndexID;
		}
		set
		{
			if ((this._IndexID != value))
			{
				this._IndexID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this._SysID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this._TableID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SysName
	{
		get
		{
			return this._SysName;
		}
		set
		{
			if ((this._SysName != value))
			{
				this._SysName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string TableName
	{
		get
		{
			return this._TableName;
		}
		set
		{
			if ((this._TableName != value))
			{
				this._TableName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemType", DbType="VarChar(50)")]
	public string SystemType
	{
		get
		{
			return this._SystemType;
		}
		set
		{
			if ((this._SystemType != value))
			{
				this._SystemType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Route
	{
		get
		{
			return this._Route;
		}
		set
		{
			if ((this._Route != value))
			{
				this._Route = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFlow", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string IsFlow
	{
		get
		{
			return this._IsFlow;
		}
		set
		{
			if ((this._IsFlow != value))
			{
				this._IsFlow = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebFormName", DbType="VarChar(50)")]
	public string WebFormName
	{
		get
		{
			return this._WebFormName;
		}
		set
		{
			if ((this._WebFormName != value))
			{
				this._WebFormName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this._FormType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeFormName", DbType="VarChar(50)")]
	public string CodeFormName
	{
		get
		{
			return this._CodeFormName;
		}
		set
		{
			if ((this._CodeFormName != value))
			{
				this._CodeFormName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(100)")]
	public string URL
	{
		get
		{
			return this._URL;
		}
		set
		{
			if ((this._URL != value))
			{
				this._URL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APLinkURL", DbType="VarChar(100)")]
	public string APLinkURL
	{
		get
		{
			return this._APLinkURL;
		}
		set
		{
			if ((this._APLinkURL != value))
			{
				this._APLinkURL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachNameList", DbType="VarChar(100)")]
	public string AttachNameList
	{
		get
		{
			return this._AttachNameList;
		}
		set
		{
			if ((this._AttachNameList != value))
			{
				this._AttachNameList = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_USER_INFO")]
public partial class BRM_USER_INFO
{
	
	private string _UserID;
	
	private string _password;
	
	private string _Name;
	
	private string _WorkStation;
	
	private string _SignLevel;
	
	private string _SignLevelDesc;
	
	private string _Mail;
	
	private string _Dept;
	
	private string _DeptCode;
	
	private System.Nullable<int> _DeptLevel;
	
	private string _Phone;
	
	private string _IsDeptManagerYN;
	
	private string _SuperiorID;
	
	private string _SuperiorName;
	
	private string _SuperiorDeptName;
	
	private string _SuperiorDeptCode;
	
	private string _AgentTurnOnYN;
	
	private string _FlagOfLeftYN;
	
	private System.Nullable<int> _SalaryID;
	
	private string _SalaryLevel;
	
	private string _NotesID;
	
	private string _FirstAgentNo;
	
	private string _SecondAgentNo;
	
	private string _ThirdAgentNo;
	
	private string _CompanyName;
	
	public BRM_USER_INFO()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this._password = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(30)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkStation", DbType="VarChar(30)")]
	public string WorkStation
	{
		get
		{
			return this._WorkStation;
		}
		set
		{
			if ((this._WorkStation != value))
			{
				this._WorkStation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignLevel", DbType="VarChar(3)")]
	public string SignLevel
	{
		get
		{
			return this._SignLevel;
		}
		set
		{
			if ((this._SignLevel != value))
			{
				this._SignLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignLevelDesc", DbType="VarChar(100)")]
	public string SignLevelDesc
	{
		get
		{
			return this._SignLevelDesc;
		}
		set
		{
			if ((this._SignLevelDesc != value))
			{
				this._SignLevelDesc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
	public string Mail
	{
		get
		{
			return this._Mail;
		}
		set
		{
			if ((this._Mail != value))
			{
				this._Mail = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="VarChar(100)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this._Dept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptCode", DbType="VarChar(10)")]
	public string DeptCode
	{
		get
		{
			return this._DeptCode;
		}
		set
		{
			if ((this._DeptCode != value))
			{
				this._DeptCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptLevel", DbType="Int")]
	public System.Nullable<int> DeptLevel
	{
		get
		{
			return this._DeptLevel;
		}
		set
		{
			if ((this._DeptLevel != value))
			{
				this._DeptLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeptManagerYN", DbType="VarChar(1)")]
	public string IsDeptManagerYN
	{
		get
		{
			return this._IsDeptManagerYN;
		}
		set
		{
			if ((this._IsDeptManagerYN != value))
			{
				this._IsDeptManagerYN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorID", DbType="VarChar(50)")]
	public string SuperiorID
	{
		get
		{
			return this._SuperiorID;
		}
		set
		{
			if ((this._SuperiorID != value))
			{
				this._SuperiorID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorName", DbType="VarChar(100)")]
	public string SuperiorName
	{
		get
		{
			return this._SuperiorName;
		}
		set
		{
			if ((this._SuperiorName != value))
			{
				this._SuperiorName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorDeptName", DbType="VarChar(50)")]
	public string SuperiorDeptName
	{
		get
		{
			return this._SuperiorDeptName;
		}
		set
		{
			if ((this._SuperiorDeptName != value))
			{
				this._SuperiorDeptName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorDeptCode", DbType="VarChar(10)")]
	public string SuperiorDeptCode
	{
		get
		{
			return this._SuperiorDeptCode;
		}
		set
		{
			if ((this._SuperiorDeptCode != value))
			{
				this._SuperiorDeptCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentTurnOnYN", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string AgentTurnOnYN
	{
		get
		{
			return this._AgentTurnOnYN;
		}
		set
		{
			if ((this._AgentTurnOnYN != value))
			{
				this._AgentTurnOnYN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagOfLeftYN", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string FlagOfLeftYN
	{
		get
		{
			return this._FlagOfLeftYN;
		}
		set
		{
			if ((this._FlagOfLeftYN != value))
			{
				this._FlagOfLeftYN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryID", DbType="Int")]
	public System.Nullable<int> SalaryID
	{
		get
		{
			return this._SalaryID;
		}
		set
		{
			if ((this._SalaryID != value))
			{
				this._SalaryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryLevel", DbType="VarChar(30)")]
	public string SalaryLevel
	{
		get
		{
			return this._SalaryLevel;
		}
		set
		{
			if ((this._SalaryLevel != value))
			{
				this._SalaryLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotesID", DbType="VarChar(50)")]
	public string NotesID
	{
		get
		{
			return this._NotesID;
		}
		set
		{
			if ((this._NotesID != value))
			{
				this._NotesID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstAgentNo", DbType="VarChar(30)")]
	public string FirstAgentNo
	{
		get
		{
			return this._FirstAgentNo;
		}
		set
		{
			if ((this._FirstAgentNo != value))
			{
				this._FirstAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondAgentNo", DbType="VarChar(30)")]
	public string SecondAgentNo
	{
		get
		{
			return this._SecondAgentNo;
		}
		set
		{
			if ((this._SecondAgentNo != value))
			{
				this._SecondAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdAgentNo", DbType="VarChar(30)")]
	public string ThirdAgentNo
	{
		get
		{
			return this._ThirdAgentNo;
		}
		set
		{
			if ((this._ThirdAgentNo != value))
			{
				this._ThirdAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50)")]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this._CompanyName = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRM_WF_Authorization")]
public partial class BRM_WF_Authorization : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ARID;
	
	private int _WFID;
	
	private string _WF_ARID;
	
	private string _FormType;
	
	private string _ARChiName;
	
	private string _AREngName;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnARIDChanging(int value);
    partial void OnARIDChanged();
    partial void OnWFIDChanging(int value);
    partial void OnWFIDChanged();
    partial void OnWF_ARIDChanging(string value);
    partial void OnWF_ARIDChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnARChiNameChanging(string value);
    partial void OnARChiNameChanged();
    partial void OnAREngNameChanging(string value);
    partial void OnAREngNameChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public BRM_WF_Authorization()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ARID
	{
		get
		{
			return this._ARID;
		}
		set
		{
			if ((this._ARID != value))
			{
				this.OnARIDChanging(value);
				this.SendPropertyChanging();
				this._ARID = value;
				this.SendPropertyChanged("ARID");
				this.OnARIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFID", DbType="Int NOT NULL")]
	public int WFID
	{
		get
		{
			return this._WFID;
		}
		set
		{
			if ((this._WFID != value))
			{
				this.OnWFIDChanging(value);
				this.SendPropertyChanging();
				this._WFID = value;
				this.SendPropertyChanged("WFID");
				this.OnWFIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WF_ARID", DbType="VarChar(50)")]
	public string WF_ARID
	{
		get
		{
			return this._WF_ARID;
		}
		set
		{
			if ((this._WF_ARID != value))
			{
				this.OnWF_ARIDChanging(value);
				this.SendPropertyChanging();
				this._WF_ARID = value;
				this.SendPropertyChanged("WF_ARID");
				this.OnWF_ARIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(50)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this.OnFormTypeChanging(value);
				this.SendPropertyChanging();
				this._FormType = value;
				this.SendPropertyChanged("FormType");
				this.OnFormTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARChiName", DbType="VarChar(50)")]
	public string ARChiName
	{
		get
		{
			return this._ARChiName;
		}
		set
		{
			if ((this._ARChiName != value))
			{
				this.OnARChiNameChanging(value);
				this.SendPropertyChanging();
				this._ARChiName = value;
				this.SendPropertyChanged("ARChiName");
				this.OnARChiNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREngName", DbType="VarChar(50)")]
	public string AREngName
	{
		get
		{
			return this._AREngName;
		}
		set
		{
			if ((this._AREngName != value))
			{
				this.OnAREngNameChanging(value);
				this.SendPropertyChanging();
				this._AREngName = value;
				this.SendPropertyChanged("AREngName");
				this.OnAREngNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(10)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.System_Manager")]
public partial class System_Manager : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Creator;
	
	private string _CreateDate;
	
	private string _SysID;
	
	private string _UserID;
	
	private string _UserName;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnSysIDChanging(string value);
    partial void OnSysIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public System_Manager()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(20)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(20)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this.OnSysIDChanging(value);
				this.SendPropertyChanging();
				this._SysID = value;
				this.SendPropertyChanged("SysID");
				this.OnSysIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
