#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GA_CarManagerment")]
public partial class CarInfoDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertList_CarManintainRecord(List_CarManintainRecord instance);
  partial void UpdateList_CarManintainRecord(List_CarManintainRecord instance);
  partial void DeleteList_CarManintainRecord(List_CarManintainRecord instance);
  #endregion
	
	public CarInfoDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GA_CarManagermentConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CarInfoDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CarInfoDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CarInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CarInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<List_CarManintainRecord> List_CarManintainRecord
	{
		get
		{
			return this.GetTable<List_CarManintainRecord>();
		}
	}
	
	public System.Data.Linq.Table<List_Dirver> List_Dirver
	{
		get
		{
			return this.GetTable<List_Dirver>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_CarManintainRecord")]
public partial class List_CarManintainRecord : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _CarNo;
	
	private System.Nullable<int> _ItemNo;
	
	private System.Nullable<System.DateTime> _MaintainDate;
	
	private string _MaintainCert;
	
	private string _Notice;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
	private string _DeleteBy;
	
	private System.Nullable<System.DateTime> _DeleteOn;
	
	private string _ModifyMan;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarNoChanging(string value);
    partial void OnCarNoChanged();
    partial void OnItemNoChanging(System.Nullable<int> value);
    partial void OnItemNoChanged();
    partial void OnMaintainDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMaintainDateChanged();
    partial void OnMaintainCertChanging(string value);
    partial void OnMaintainCertChanged();
    partial void OnNoticeChanging(string value);
    partial void OnNoticeChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnDeleteByChanging(string value);
    partial void OnDeleteByChanged();
    partial void OnDeleteOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteOnChanged();
    partial void OnModifyManChanging(string value);
    partial void OnModifyManChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    #endregion
	
	public List_CarManintainRecord()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarNo", DbType="NChar(20)")]
	public string CarNo
	{
		get
		{
			return this._CarNo;
		}
		set
		{
			if ((this._CarNo != value))
			{
				this.OnCarNoChanging(value);
				this.SendPropertyChanging();
				this._CarNo = value;
				this.SendPropertyChanged("CarNo");
				this.OnCarNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNo", DbType="Int")]
	public System.Nullable<int> ItemNo
	{
		get
		{
			return this._ItemNo;
		}
		set
		{
			if ((this._ItemNo != value))
			{
				this.OnItemNoChanging(value);
				this.SendPropertyChanging();
				this._ItemNo = value;
				this.SendPropertyChanged("ItemNo");
				this.OnItemNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintainDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> MaintainDate
	{
		get
		{
			return this._MaintainDate;
		}
		set
		{
			if ((this._MaintainDate != value))
			{
				this.OnMaintainDateChanging(value);
				this.SendPropertyChanging();
				this._MaintainDate = value;
				this.SendPropertyChanged("MaintainDate");
				this.OnMaintainDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintainCert", DbType="NChar(200)")]
	public string MaintainCert
	{
		get
		{
			return this._MaintainCert;
		}
		set
		{
			if ((this._MaintainCert != value))
			{
				this.OnMaintainCertChanging(value);
				this.SendPropertyChanging();
				this._MaintainCert = value;
				this.SendPropertyChanged("MaintainCert");
				this.OnMaintainCertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notice", DbType="NChar(500)")]
	public string Notice
	{
		get
		{
			return this._Notice;
		}
		set
		{
			if ((this._Notice != value))
			{
				this.OnNoticeChanging(value);
				this.SendPropertyChanging();
				this._Notice = value;
				this.SendPropertyChanged("Notice");
				this.OnNoticeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(20)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="VarChar(20)")]
	public string DeleteBy
	{
		get
		{
			return this._DeleteBy;
		}
		set
		{
			if ((this._DeleteBy != value))
			{
				this.OnDeleteByChanging(value);
				this.SendPropertyChanging();
				this._DeleteBy = value;
				this.SendPropertyChanged("DeleteBy");
				this.OnDeleteByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeleteOn
	{
		get
		{
			return this._DeleteOn;
		}
		set
		{
			if ((this._DeleteOn != value))
			{
				this.OnDeleteOnChanging(value);
				this.SendPropertyChanging();
				this._DeleteOn = value;
				this.SendPropertyChanged("DeleteOn");
				this.OnDeleteOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyMan", DbType="VarChar(20)")]
	public string ModifyMan
	{
		get
		{
			return this._ModifyMan;
		}
		set
		{
			if ((this._ModifyMan != value))
			{
				this.OnModifyManChanging(value);
				this.SendPropertyChanging();
				this._ModifyMan = value;
				this.SendPropertyChanged("ModifyMan");
				this.OnModifyManChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_Dirver")]
public partial class List_Dirver
{
	
	private int _ID;
	
	private string _FactoryArea;
	
	private string _CarNo;
	
	private string _DriverName;
	
	private string _DriverPhoneNo;
	
	private string _Brand;
	
	private string _Remark;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
	private string _DeleteBy;
	
	private System.Nullable<System.DateTime> _DeleteOn;
	
	private string _ModifyMan;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	public List_Dirver()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryArea", DbType="NChar(20)")]
	public string FactoryArea
	{
		get
		{
			return this._FactoryArea;
		}
		set
		{
			if ((this._FactoryArea != value))
			{
				this._FactoryArea = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarNo", DbType="VarChar(50)")]
	public string CarNo
	{
		get
		{
			return this._CarNo;
		}
		set
		{
			if ((this._CarNo != value))
			{
				this._CarNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverName", DbType="NVarChar(50)")]
	public string DriverName
	{
		get
		{
			return this._DriverName;
		}
		set
		{
			if ((this._DriverName != value))
			{
				this._DriverName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverPhoneNo", DbType="NVarChar(50)")]
	public string DriverPhoneNo
	{
		get
		{
			return this._DriverPhoneNo;
		}
		set
		{
			if ((this._DriverPhoneNo != value))
			{
				this._DriverPhoneNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="NVarChar(50)")]
	public string Brand
	{
		get
		{
			return this._Brand;
		}
		set
		{
			if ((this._Brand != value))
			{
				this._Brand = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(500)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this._Remark = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="NVarChar(50)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this._Creator = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this._CreateDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="NChar(10)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(20)")]
	public string DeleteBy
	{
		get
		{
			return this._DeleteBy;
		}
		set
		{
			if ((this._DeleteBy != value))
			{
				this._DeleteBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeleteOn
	{
		get
		{
			return this._DeleteOn;
		}
		set
		{
			if ((this._DeleteOn != value))
			{
				this._DeleteOn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyMan", DbType="NVarChar(50)")]
	public string ModifyMan
	{
		get
		{
			return this._ModifyMan;
		}
		set
		{
			if ((this._ModifyMan != value))
			{
				this._ModifyMan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this._ModifyDate = value;
			}
		}
	}
}
#pragma warning restore 1591
