#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IE_ProjectBudget")]
public partial class PBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertItem_BudgetFIN(Item_BudgetFIN instance);
  partial void UpdateItem_BudgetFIN(Item_BudgetFIN instance);
  partial void DeleteItem_BudgetFIN(Item_BudgetFIN instance);
  partial void InsertItem_BudgetType(Item_BudgetType instance);
  partial void UpdateItem_BudgetType(Item_BudgetType instance);
  partial void DeleteItem_BudgetType(Item_BudgetType instance);
  partial void InsertItem_StartCode(Item_StartCode instance);
  partial void UpdateItem_StartCode(Item_StartCode instance);
  partial void DeleteItem_StartCode(Item_StartCode instance);
  partial void InsertList_ProjectBudget(List_ProjectBudget instance);
  partial void UpdateList_ProjectBudget(List_ProjectBudget instance);
  partial void DeleteList_ProjectBudget(List_ProjectBudget instance);
  partial void InsertItem_EndCode(Item_EndCode instance);
  partial void UpdateItem_EndCode(Item_EndCode instance);
  partial void DeleteItem_EndCode(Item_EndCode instance);
  partial void InsertList_SysSignMan(List_SysSignMan instance);
  partial void UpdateList_SysSignMan(List_SysSignMan instance);
  partial void DeleteList_SysSignMan(List_SysSignMan instance);
  partial void InsertList_ProjectBudget_Add(List_ProjectBudget_Add instance);
  partial void UpdateList_ProjectBudget_Add(List_ProjectBudget_Add instance);
  partial void DeleteList_ProjectBudget_Add(List_ProjectBudget_Add instance);
  partial void InsertList_SysManager(List_SysManager instance);
  partial void UpdateList_SysManager(List_SysManager instance);
  partial void DeleteList_SysManager(List_SysManager instance);
  partial void InsertFormProjectBudget(FormProjectBudget instance);
  partial void UpdateFormProjectBudget(FormProjectBudget instance);
  partial void DeleteFormProjectBudget(FormProjectBudget instance);
  #endregion
	
	public PBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["IE_ProjectBudgetConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Item_BudgetCurrency> Item_BudgetCurrency
	{
		get
		{
			return this.GetTable<Item_BudgetCurrency>();
		}
	}
	
	public System.Data.Linq.Table<Item_BudgetFIN> Item_BudgetFIN
	{
		get
		{
			return this.GetTable<Item_BudgetFIN>();
		}
	}
	
	public System.Data.Linq.Table<Item_BudgetType> Item_BudgetType
	{
		get
		{
			return this.GetTable<Item_BudgetType>();
		}
	}
	
	public System.Data.Linq.Table<Item_StartCode> Item_StartCode
	{
		get
		{
			return this.GetTable<Item_StartCode>();
		}
	}
	
	public System.Data.Linq.Table<List_ProjectBudget> List_ProjectBudget
	{
		get
		{
			return this.GetTable<List_ProjectBudget>();
		}
	}
	
	public System.Data.Linq.Table<Item_EndCode> Item_EndCode
	{
		get
		{
			return this.GetTable<Item_EndCode>();
		}
	}
	
	public System.Data.Linq.Table<V_EPS_FormInFlow> V_EPS_FormInFlow
	{
		get
		{
			return this.GetTable<V_EPS_FormInFlow>();
		}
	}
	
	public System.Data.Linq.Table<V_EPS_FormEnd> V_EPS_FormEnd
	{
		get
		{
			return this.GetTable<V_EPS_FormEnd>();
		}
	}
	
	public System.Data.Linq.Table<V_EPS_FormResendList> V_EPS_FormResendList
	{
		get
		{
			return this.GetTable<V_EPS_FormResendList>();
		}
	}
	
	public System.Data.Linq.Table<List_SysSignMan> List_SysSignMan
	{
		get
		{
			return this.GetTable<List_SysSignMan>();
		}
	}
	
	public System.Data.Linq.Table<List_ProjectBudget_Add> List_ProjectBudget_Add
	{
		get
		{
			return this.GetTable<List_ProjectBudget_Add>();
		}
	}
	
	public System.Data.Linq.Table<List_NoticeMan> List_NoticeMan
	{
		get
		{
			return this.GetTable<List_NoticeMan>();
		}
	}
	
	public System.Data.Linq.Table<List_SysManager> List_SysManager
	{
		get
		{
			return this.GetTable<List_SysManager>();
		}
	}
	
	public System.Data.Linq.Table<FormProjectBudget> FormProjectBudget
	{
		get
		{
			return this.GetTable<FormProjectBudget>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_BudgetCurrency")]
public partial class Item_BudgetCurrency
{
	
	private string _BudgetCurrency;
	
	private string _BudgetCurrencyName;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
	public Item_BudgetCurrency()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetCurrency", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string BudgetCurrency
	{
		get
		{
			return this._BudgetCurrency;
		}
		set
		{
			if ((this._BudgetCurrency != value))
			{
				this._BudgetCurrency = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetCurrencyName", DbType="VarChar(30)")]
	public string BudgetCurrencyName
	{
		get
		{
			return this._BudgetCurrencyName;
		}
		set
		{
			if ((this._BudgetCurrencyName != value))
			{
				this._BudgetCurrencyName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this._Creator = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this._CreateDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_BudgetFIN")]
public partial class Item_BudgetFIN : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _FactoryCode;
	
	private string _FactoryName;
	
	private string _FactoryBudgetFINID;
	
	private string _FactoryBudgetFINName;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFactoryCodeChanging(string value);
    partial void OnFactoryCodeChanged();
    partial void OnFactoryNameChanging(string value);
    partial void OnFactoryNameChanged();
    partial void OnFactoryBudgetFINIDChanging(string value);
    partial void OnFactoryBudgetFINIDChanged();
    partial void OnFactoryBudgetFINNameChanging(string value);
    partial void OnFactoryBudgetFINNameChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public Item_BudgetFIN()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryCode", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string FactoryCode
	{
		get
		{
			return this._FactoryCode;
		}
		set
		{
			if ((this._FactoryCode != value))
			{
				this.OnFactoryCodeChanging(value);
				this.SendPropertyChanging();
				this._FactoryCode = value;
				this.SendPropertyChanged("FactoryCode");
				this.OnFactoryCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryName", DbType="VarChar(30)")]
	public string FactoryName
	{
		get
		{
			return this._FactoryName;
		}
		set
		{
			if ((this._FactoryName != value))
			{
				this.OnFactoryNameChanging(value);
				this.SendPropertyChanging();
				this._FactoryName = value;
				this.SendPropertyChanged("FactoryName");
				this.OnFactoryNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryBudgetFINID", DbType="VarChar(30)")]
	public string FactoryBudgetFINID
	{
		get
		{
			return this._FactoryBudgetFINID;
		}
		set
		{
			if ((this._FactoryBudgetFINID != value))
			{
				this.OnFactoryBudgetFINIDChanging(value);
				this.SendPropertyChanging();
				this._FactoryBudgetFINID = value;
				this.SendPropertyChanged("FactoryBudgetFINID");
				this.OnFactoryBudgetFINIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryBudgetFINName", DbType="VarChar(50)")]
	public string FactoryBudgetFINName
	{
		get
		{
			return this._FactoryBudgetFINName;
		}
		set
		{
			if ((this._FactoryBudgetFINName != value))
			{
				this.OnFactoryBudgetFINNameChanging(value);
				this.SendPropertyChanging();
				this._FactoryBudgetFINName = value;
				this.SendPropertyChanged("FactoryBudgetFINName");
				this.OnFactoryBudgetFINNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_BudgetType")]
public partial class Item_BudgetType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _BudgetTypeCode;
	
	private string _BudgetTypeName;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBudgetTypeCodeChanging(string value);
    partial void OnBudgetTypeCodeChanged();
    partial void OnBudgetTypeNameChanging(string value);
    partial void OnBudgetTypeNameChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public Item_BudgetType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTypeCode", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string BudgetTypeCode
	{
		get
		{
			return this._BudgetTypeCode;
		}
		set
		{
			if ((this._BudgetTypeCode != value))
			{
				this.OnBudgetTypeCodeChanging(value);
				this.SendPropertyChanging();
				this._BudgetTypeCode = value;
				this.SendPropertyChanged("BudgetTypeCode");
				this.OnBudgetTypeCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTypeName", DbType="VarChar(50)")]
	public string BudgetTypeName
	{
		get
		{
			return this._BudgetTypeName;
		}
		set
		{
			if ((this._BudgetTypeName != value))
			{
				this.OnBudgetTypeNameChanging(value);
				this.SendPropertyChanging();
				this._BudgetTypeName = value;
				this.SendPropertyChanged("BudgetTypeName");
				this.OnBudgetTypeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_StartCode")]
public partial class Item_StartCode : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _StartCode;
	
	private string _StartCodeName;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStartCodeChanging(string value);
    partial void OnStartCodeChanged();
    partial void OnStartCodeNameChanging(string value);
    partial void OnStartCodeNameChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public Item_StartCode()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCode", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string StartCode
	{
		get
		{
			return this._StartCode;
		}
		set
		{
			if ((this._StartCode != value))
			{
				this.OnStartCodeChanging(value);
				this.SendPropertyChanging();
				this._StartCode = value;
				this.SendPropertyChanged("StartCode");
				this.OnStartCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCodeName", DbType="VarChar(30)")]
	public string StartCodeName
	{
		get
		{
			return this._StartCodeName;
		}
		set
		{
			if ((this._StartCodeName != value))
			{
				this.OnStartCodeNameChanging(value);
				this.SendPropertyChanging();
				this._StartCodeName = value;
				this.SendPropertyChanged("StartCodeName");
				this.OnStartCodeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_ProjectBudget")]
public partial class List_ProjectBudget : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BudgetID;
	
	private string _FormNo;
	
	private string _ProjectCode;
	
	private string _BudgetType;
	
	private string _OUCode;
	
	private string _Description;
	
	private double _Money;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
	private string _ModifyMan;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBudgetIDChanging(int value);
    partial void OnBudgetIDChanged();
    partial void OnFormNoChanging(string value);
    partial void OnFormNoChanged();
    partial void OnProjectCodeChanging(string value);
    partial void OnProjectCodeChanged();
    partial void OnBudgetTypeChanging(string value);
    partial void OnBudgetTypeChanged();
    partial void OnOUCodeChanging(string value);
    partial void OnOUCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMoneyChanging(double value);
    partial void OnMoneyChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnModifyManChanging(string value);
    partial void OnModifyManChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    #endregion
	
	public List_ProjectBudget()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BudgetID
	{
		get
		{
			return this._BudgetID;
		}
		set
		{
			if ((this._BudgetID != value))
			{
				this.OnBudgetIDChanging(value);
				this.SendPropertyChanging();
				this._BudgetID = value;
				this.SendPropertyChanged("BudgetID");
				this.OnBudgetIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this.OnFormNoChanging(value);
				this.SendPropertyChanging();
				this._FormNo = value;
				this.SendPropertyChanged("FormNo");
				this.OnFormNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string ProjectCode
	{
		get
		{
			return this._ProjectCode;
		}
		set
		{
			if ((this._ProjectCode != value))
			{
				this.OnProjectCodeChanging(value);
				this.SendPropertyChanging();
				this._ProjectCode = value;
				this.SendPropertyChanged("ProjectCode");
				this.OnProjectCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string BudgetType
	{
		get
		{
			return this._BudgetType;
		}
		set
		{
			if ((this._BudgetType != value))
			{
				this.OnBudgetTypeChanging(value);
				this.SendPropertyChanging();
				this._BudgetType = value;
				this.SendPropertyChanged("BudgetType");
				this.OnBudgetTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUCode", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string OUCode
	{
		get
		{
			return this._OUCode;
		}
		set
		{
			if ((this._OUCode != value))
			{
				this.OnOUCodeChanging(value);
				this.SendPropertyChanging();
				this._OUCode = value;
				this.SendPropertyChanged("OUCode");
				this.OnOUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(200)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="Float NOT NULL")]
	public double Money
	{
		get
		{
			return this._Money;
		}
		set
		{
			if ((this._Money != value))
			{
				this.OnMoneyChanging(value);
				this.SendPropertyChanging();
				this._Money = value;
				this.SendPropertyChanged("Money");
				this.OnMoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyMan", DbType="VarChar(30)")]
	public string ModifyMan
	{
		get
		{
			return this._ModifyMan;
		}
		set
		{
			if ((this._ModifyMan != value))
			{
				this.OnModifyManChanging(value);
				this.SendPropertyChanging();
				this._ModifyMan = value;
				this.SendPropertyChanged("ModifyMan");
				this.OnModifyManChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_EndCode")]
public partial class Item_EndCode : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _StartCode;
	
	private string _EndCode;
	
	private string _EndCodeName;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStartCodeChanging(string value);
    partial void OnStartCodeChanged();
    partial void OnEndCodeChanging(string value);
    partial void OnEndCodeChanged();
    partial void OnEndCodeNameChanging(string value);
    partial void OnEndCodeNameChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    #endregion
	
	public Item_EndCode()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCode", DbType="VarChar(2)")]
	public string StartCode
	{
		get
		{
			return this._StartCode;
		}
		set
		{
			if ((this._StartCode != value))
			{
				this.OnStartCodeChanging(value);
				this.SendPropertyChanging();
				this._StartCode = value;
				this.SendPropertyChanged("StartCode");
				this.OnStartCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndCode", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string EndCode
	{
		get
		{
			return this._EndCode;
		}
		set
		{
			if ((this._EndCode != value))
			{
				this.OnEndCodeChanging(value);
				this.SendPropertyChanging();
				this._EndCode = value;
				this.SendPropertyChanged("EndCode");
				this.OnEndCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndCodeName", DbType="VarChar(30)")]
	public string EndCodeName
	{
		get
		{
			return this._EndCodeName;
		}
		set
		{
			if ((this._EndCodeName != value))
			{
				this.OnEndCodeNameChanging(value);
				this.SendPropertyChanging();
				this._EndCodeName = value;
				this.SendPropertyChanged("EndCodeName");
				this.OnEndCodeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EPS_FormInFlow")]
public partial class V_EPS_FormInFlow
{
	
	private int _FormID;
	
	private string _FormNo;
	
	private string _FormType;
	
	private string _FormTypeName;
	
	private System.Nullable<int> _NodeSeq;
	
	private string _Form_Status;
	
	private string _ApplyManNo;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
	private System.Nullable<System.DateTime> _ApplyDate;
	
	private string _OwnerList;
	
	private string _DeleteFlag;
	
	private string _AgentID;
	
	private string _FormUrl;
	
	public V_EPS_FormInFlow()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int NOT NULL")]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this._FormID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(30)")]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this._FormNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(30)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this._FormType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTypeName", DbType="VarChar(50)")]
	public string FormTypeName
	{
		get
		{
			return this._FormTypeName;
		}
		set
		{
			if ((this._FormTypeName != value))
			{
				this._FormTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int")]
	public System.Nullable<int> NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this._NodeSeq = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form_Status", DbType="NVarChar(50)")]
	public string Form_Status
	{
		get
		{
			return this._Form_Status;
		}
		set
		{
			if ((this._Form_Status != value))
			{
				this._Form_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyManNo", DbType="VarChar(10)")]
	public string ApplyManNo
	{
		get
		{
			return this._ApplyManNo;
		}
		set
		{
			if ((this._ApplyManNo != value))
			{
				this._ApplyManNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this._UpdateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ApplyDate
	{
		get
		{
			return this._ApplyDate;
		}
		set
		{
			if ((this._ApplyDate != value))
			{
				this._ApplyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerList", DbType="VarChar(100)")]
	public string OwnerList
	{
		get
		{
			return this._OwnerList;
		}
		set
		{
			if ((this._OwnerList != value))
			{
				this._OwnerList = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="VarChar(30)")]
	public string AgentID
	{
		get
		{
			return this._AgentID;
		}
		set
		{
			if ((this._AgentID != value))
			{
				this._AgentID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="VarChar(50)")]
	public string FormUrl
	{
		get
		{
			return this._FormUrl;
		}
		set
		{
			if ((this._FormUrl != value))
			{
				this._FormUrl = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EPS_FormEnd")]
public partial class V_EPS_FormEnd
{
	
	private int _FormID;
	
	private string _FormNo;
	
	private string _FormType;
	
	private string _FormTypeName;
	
	private int _NodeSeq;
	
	private string _Form_Status;
	
	private string _ApplyManNo;
	
	private string _FactoryArea;
	
	private string _Register_Name;
	
	private System.Nullable<System.DateTime> _ApplyDate;
	
	private string _ApplyDept;
	
	private string _TheOwner;
	
	private string _TheOwner_Name;
	
	private System.Nullable<int> _NextSeq;
	
	private string _DeleteFlag;
	
	private string _SysID;
	
	private string _TableID;
	
	private string _FormURL;
	
	private string _URL;
	
	public V_EPS_FormEnd()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int NOT NULL")]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this._FormID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(30)")]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this._FormNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(30)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this._FormType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTypeName", DbType="VarChar(50)")]
	public string FormTypeName
	{
		get
		{
			return this._FormTypeName;
		}
		set
		{
			if ((this._FormTypeName != value))
			{
				this._FormTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int NOT NULL")]
	public int NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this._NodeSeq = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form_Status", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
	public string Form_Status
	{
		get
		{
			return this._Form_Status;
		}
		set
		{
			if ((this._Form_Status != value))
			{
				this._Form_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyManNo", DbType="VarChar(10)")]
	public string ApplyManNo
	{
		get
		{
			return this._ApplyManNo;
		}
		set
		{
			if ((this._ApplyManNo != value))
			{
				this._ApplyManNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryArea", DbType="VarChar(30)")]
	public string FactoryArea
	{
		get
		{
			return this._FactoryArea;
		}
		set
		{
			if ((this._FactoryArea != value))
			{
				this._FactoryArea = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Register_Name", DbType="VarChar(41)")]
	public string Register_Name
	{
		get
		{
			return this._Register_Name;
		}
		set
		{
			if ((this._Register_Name != value))
			{
				this._Register_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ApplyDate
	{
		get
		{
			return this._ApplyDate;
		}
		set
		{
			if ((this._ApplyDate != value))
			{
				this._ApplyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDept", DbType="VarChar(50)")]
	public string ApplyDept
	{
		get
		{
			return this._ApplyDept;
		}
		set
		{
			if ((this._ApplyDept != value))
			{
				this._ApplyDept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOwner", DbType="VarChar(50)")]
	public string TheOwner
	{
		get
		{
			return this._TheOwner;
		}
		set
		{
			if ((this._TheOwner != value))
			{
				this._TheOwner = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOwner_Name", DbType="NVarChar(101)")]
	public string TheOwner_Name
	{
		get
		{
			return this._TheOwner_Name;
		}
		set
		{
			if ((this._TheOwner_Name != value))
			{
				this._TheOwner_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextSeq", DbType="Int")]
	public System.Nullable<int> NextSeq
	{
		get
		{
			return this._NextSeq;
		}
		set
		{
			if ((this._NextSeq != value))
			{
				this._NextSeq = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(10)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this._SysID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(10)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this._TableID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormURL", DbType="VarChar(50)")]
	public string FormURL
	{
		get
		{
			return this._FormURL;
		}
		set
		{
			if ((this._FormURL != value))
			{
				this._FormURL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(269)")]
	public string URL
	{
		get
		{
			return this._URL;
		}
		set
		{
			if ((this._URL != value))
			{
				this._URL = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EPS_FormResendList")]
public partial class V_EPS_FormResendList
{
	
	private int _FormID;
	
	private string _FormType;
	
	private System.Nullable<int> _NodeSeq;
	
	private string _NodeName;
	
	private string _LastAction;
	
	private string _LastOwner;
	
	private string _OwnerList;
	
	private string _OwnerListName;
	
	private string _TheOwner;
	
	private System.Nullable<char> _WFClosed;
	
	private string _Expr1;
	
	private System.Nullable<System.DateTime> _ApplyDate;
	
	private string _FormTypeName;
	
	private string _ApplyDept;
	
	private string _ApplyManNo;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	private string _DeleteFlag;
	
	private string _UserID;
	
	private string _Name;
	
	private string _FirstAgentNo;
	
	private string _SecondAgentNo;
	
	private string _ThirdAgentNo;
	
	private string _FormUrl;
	
	private string _SysID;
	
	private string _TableID;
	
	private string _AgentID;
	
	public V_EPS_FormResendList()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int NOT NULL")]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this._FormID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(30)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this._FormType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeSeq", DbType="Int")]
	public System.Nullable<int> NodeSeq
	{
		get
		{
			return this._NodeSeq;
		}
		set
		{
			if ((this._NodeSeq != value))
			{
				this._NodeSeq = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(50)")]
	public string NodeName
	{
		get
		{
			return this._NodeName;
		}
		set
		{
			if ((this._NodeName != value))
			{
				this._NodeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAction", DbType="VarChar(50)")]
	public string LastAction
	{
		get
		{
			return this._LastAction;
		}
		set
		{
			if ((this._LastAction != value))
			{
				this._LastAction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastOwner", DbType="VarChar(50)")]
	public string LastOwner
	{
		get
		{
			return this._LastOwner;
		}
		set
		{
			if ((this._LastOwner != value))
			{
				this._LastOwner = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerList", DbType="VarChar(100)")]
	public string OwnerList
	{
		get
		{
			return this._OwnerList;
		}
		set
		{
			if ((this._OwnerList != value))
			{
				this._OwnerList = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerListName", DbType="NVarChar(152)")]
	public string OwnerListName
	{
		get
		{
			return this._OwnerListName;
		}
		set
		{
			if ((this._OwnerListName != value))
			{
				this._OwnerListName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOwner", DbType="VarChar(50)")]
	public string TheOwner
	{
		get
		{
			return this._TheOwner;
		}
		set
		{
			if ((this._TheOwner != value))
			{
				this._TheOwner = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFClosed", DbType="Char(1)")]
	public System.Nullable<char> WFClosed
	{
		get
		{
			return this._WFClosed;
		}
		set
		{
			if ((this._WFClosed != value))
			{
				this._WFClosed = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="VarChar(30)")]
	public string Expr1
	{
		get
		{
			return this._Expr1;
		}
		set
		{
			if ((this._Expr1 != value))
			{
				this._Expr1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ApplyDate
	{
		get
		{
			return this._ApplyDate;
		}
		set
		{
			if ((this._ApplyDate != value))
			{
				this._ApplyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTypeName", DbType="VarChar(50)")]
	public string FormTypeName
	{
		get
		{
			return this._FormTypeName;
		}
		set
		{
			if ((this._FormTypeName != value))
			{
				this._FormTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDept", DbType="VarChar(50)")]
	public string ApplyDept
	{
		get
		{
			return this._ApplyDept;
		}
		set
		{
			if ((this._ApplyDept != value))
			{
				this._ApplyDept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyManNo", DbType="VarChar(10)")]
	public string ApplyManNo
	{
		get
		{
			return this._ApplyManNo;
		}
		set
		{
			if ((this._ApplyManNo != value))
			{
				this._ApplyManNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this._ModifyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this._DeleteFlag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(10)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(30)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstAgentNo", DbType="VarChar(30)")]
	public string FirstAgentNo
	{
		get
		{
			return this._FirstAgentNo;
		}
		set
		{
			if ((this._FirstAgentNo != value))
			{
				this._FirstAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondAgentNo", DbType="VarChar(30)")]
	public string SecondAgentNo
	{
		get
		{
			return this._SecondAgentNo;
		}
		set
		{
			if ((this._SecondAgentNo != value))
			{
				this._SecondAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdAgentNo", DbType="VarChar(30)")]
	public string ThirdAgentNo
	{
		get
		{
			return this._ThirdAgentNo;
		}
		set
		{
			if ((this._ThirdAgentNo != value))
			{
				this._ThirdAgentNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="VarChar(50)")]
	public string FormUrl
	{
		get
		{
			return this._FormUrl;
		}
		set
		{
			if ((this._FormUrl != value))
			{
				this._FormUrl = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(10)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this._SysID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(10)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this._TableID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="VarChar(30)")]
	public string AgentID
	{
		get
		{
			return this._AgentID;
		}
		set
		{
			if ((this._AgentID != value))
			{
				this._AgentID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_SysSignMan")]
public partial class List_SysSignMan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TableRole;
	
	private string _FactoryArea;
	
	private string _UserID;
	
	private string _UserName;
	
	private string _TableID;
	
	private string _DeleteFlag;
	
	private string _DeleteBy;
	
	private System.Nullable<System.DateTime> _DeleteOn;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTableRoleChanging(string value);
    partial void OnTableRoleChanged();
    partial void OnFactoryAreaChanging(string value);
    partial void OnFactoryAreaChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnDeleteByChanging(string value);
    partial void OnDeleteByChanged();
    partial void OnDeleteOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteOnChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public List_SysSignMan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableRole", DbType="VarChar(50)")]
	public string TableRole
	{
		get
		{
			return this._TableRole;
		}
		set
		{
			if ((this._TableRole != value))
			{
				this.OnTableRoleChanging(value);
				this.SendPropertyChanging();
				this._TableRole = value;
				this.SendPropertyChanged("TableRole");
				this.OnTableRoleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryArea", DbType="VarChar(10)")]
	public string FactoryArea
	{
		get
		{
			return this._FactoryArea;
		}
		set
		{
			if ((this._FactoryArea != value))
			{
				this.OnFactoryAreaChanging(value);
				this.SendPropertyChanging();
				this._FactoryArea = value;
				this.SendPropertyChanged("FactoryArea");
				this.OnFactoryAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(30)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(30)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this.OnTableIDChanging(value);
				this.SendPropertyChanging();
				this._TableID = value;
				this.SendPropertyChanged("TableID");
				this.OnTableIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="VarChar(30)")]
	public string DeleteBy
	{
		get
		{
			return this._DeleteBy;
		}
		set
		{
			if ((this._DeleteBy != value))
			{
				this.OnDeleteByChanging(value);
				this.SendPropertyChanging();
				this._DeleteBy = value;
				this.SendPropertyChanged("DeleteBy");
				this.OnDeleteByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeleteOn
	{
		get
		{
			return this._DeleteOn;
		}
		set
		{
			if ((this._DeleteOn != value))
			{
				this.OnDeleteOnChanging(value);
				this.SendPropertyChanging();
				this._DeleteOn = value;
				this.SendPropertyChanged("DeleteOn");
				this.OnDeleteOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_ProjectBudget_Add")]
public partial class List_ProjectBudget_Add : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BudgetID;
	
	private System.Nullable<int> _ItemNo;
	
	private string _FormNo;
	
	private string _ProjectCode;
	
	private string _BudgetType;
	
	private string _OUCode;
	
	private string _Description;
	
	private System.Nullable<double> _Past_Money;
	
	private System.Nullable<double> _This_Money;
	
	private System.Nullable<double> _Sec_Money;
	
	private System.Nullable<double> _Thi_Money;
	
	private System.Nullable<double> _Total_Money;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _DeleteFlag;
	
	private string _ModifyMan;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBudgetIDChanging(int value);
    partial void OnBudgetIDChanged();
    partial void OnItemNoChanging(System.Nullable<int> value);
    partial void OnItemNoChanged();
    partial void OnFormNoChanging(string value);
    partial void OnFormNoChanged();
    partial void OnProjectCodeChanging(string value);
    partial void OnProjectCodeChanged();
    partial void OnBudgetTypeChanging(string value);
    partial void OnBudgetTypeChanged();
    partial void OnOUCodeChanging(string value);
    partial void OnOUCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPast_MoneyChanging(System.Nullable<double> value);
    partial void OnPast_MoneyChanged();
    partial void OnThis_MoneyChanging(System.Nullable<double> value);
    partial void OnThis_MoneyChanged();
    partial void OnSec_MoneyChanging(System.Nullable<double> value);
    partial void OnSec_MoneyChanged();
    partial void OnThi_MoneyChanging(System.Nullable<double> value);
    partial void OnThi_MoneyChanged();
    partial void OnTotal_MoneyChanging(System.Nullable<double> value);
    partial void OnTotal_MoneyChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnModifyManChanging(string value);
    partial void OnModifyManChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    #endregion
	
	public List_ProjectBudget_Add()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BudgetID
	{
		get
		{
			return this._BudgetID;
		}
		set
		{
			if ((this._BudgetID != value))
			{
				this.OnBudgetIDChanging(value);
				this.SendPropertyChanging();
				this._BudgetID = value;
				this.SendPropertyChanged("BudgetID");
				this.OnBudgetIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNo", DbType="Int")]
	public System.Nullable<int> ItemNo
	{
		get
		{
			return this._ItemNo;
		}
		set
		{
			if ((this._ItemNo != value))
			{
				this.OnItemNoChanging(value);
				this.SendPropertyChanging();
				this._ItemNo = value;
				this.SendPropertyChanged("ItemNo");
				this.OnItemNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this.OnFormNoChanging(value);
				this.SendPropertyChanging();
				this._FormNo = value;
				this.SendPropertyChanged("FormNo");
				this.OnFormNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string ProjectCode
	{
		get
		{
			return this._ProjectCode;
		}
		set
		{
			if ((this._ProjectCode != value))
			{
				this.OnProjectCodeChanging(value);
				this.SendPropertyChanging();
				this._ProjectCode = value;
				this.SendPropertyChanged("ProjectCode");
				this.OnProjectCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string BudgetType
	{
		get
		{
			return this._BudgetType;
		}
		set
		{
			if ((this._BudgetType != value))
			{
				this.OnBudgetTypeChanging(value);
				this.SendPropertyChanging();
				this._BudgetType = value;
				this.SendPropertyChanged("BudgetType");
				this.OnBudgetTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUCode", DbType="VarChar(30)")]
	public string OUCode
	{
		get
		{
			return this._OUCode;
		}
		set
		{
			if ((this._OUCode != value))
			{
				this.OnOUCodeChanging(value);
				this.SendPropertyChanging();
				this._OUCode = value;
				this.SendPropertyChanged("OUCode");
				this.OnOUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(200)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Past_Money", DbType="Float")]
	public System.Nullable<double> Past_Money
	{
		get
		{
			return this._Past_Money;
		}
		set
		{
			if ((this._Past_Money != value))
			{
				this.OnPast_MoneyChanging(value);
				this.SendPropertyChanging();
				this._Past_Money = value;
				this.SendPropertyChanged("Past_Money");
				this.OnPast_MoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_This_Money", DbType="Float")]
	public System.Nullable<double> This_Money
	{
		get
		{
			return this._This_Money;
		}
		set
		{
			if ((this._This_Money != value))
			{
				this.OnThis_MoneyChanging(value);
				this.SendPropertyChanging();
				this._This_Money = value;
				this.SendPropertyChanged("This_Money");
				this.OnThis_MoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sec_Money", DbType="Float")]
	public System.Nullable<double> Sec_Money
	{
		get
		{
			return this._Sec_Money;
		}
		set
		{
			if ((this._Sec_Money != value))
			{
				this.OnSec_MoneyChanging(value);
				this.SendPropertyChanging();
				this._Sec_Money = value;
				this.SendPropertyChanged("Sec_Money");
				this.OnSec_MoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thi_Money", DbType="Float")]
	public System.Nullable<double> Thi_Money
	{
		get
		{
			return this._Thi_Money;
		}
		set
		{
			if ((this._Thi_Money != value))
			{
				this.OnThi_MoneyChanging(value);
				this.SendPropertyChanging();
				this._Thi_Money = value;
				this.SendPropertyChanged("Thi_Money");
				this.OnThi_MoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Money", DbType="Float")]
	public System.Nullable<double> Total_Money
	{
		get
		{
			return this._Total_Money;
		}
		set
		{
			if ((this._Total_Money != value))
			{
				this.OnTotal_MoneyChanging(value);
				this.SendPropertyChanging();
				this._Total_Money = value;
				this.SendPropertyChanged("Total_Money");
				this.OnTotal_MoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyMan", DbType="VarChar(30)")]
	public string ModifyMan
	{
		get
		{
			return this._ModifyMan;
		}
		set
		{
			if ((this._ModifyMan != value))
			{
				this.OnModifyManChanging(value);
				this.SendPropertyChanging();
				this._ModifyMan = value;
				this.SendPropertyChanged("ModifyMan");
				this.OnModifyManChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_NoticeMan")]
public partial class List_NoticeMan
{
	
	private int _NoticeManID;
	
	private string _NoticeTypeValue;
	
	private string _NoticeTypeName;
	
	private string _MailType;
	
	private string _MailTo;
	
	private string _Notes;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	public List_NoticeMan()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeManID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int NoticeManID
	{
		get
		{
			return this._NoticeManID;
		}
		set
		{
			if ((this._NoticeManID != value))
			{
				this._NoticeManID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeTypeValue", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string NoticeTypeValue
	{
		get
		{
			return this._NoticeTypeValue;
		}
		set
		{
			if ((this._NoticeTypeValue != value))
			{
				this._NoticeTypeValue = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeTypeName", DbType="VarChar(30)")]
	public string NoticeTypeName
	{
		get
		{
			return this._NoticeTypeName;
		}
		set
		{
			if ((this._NoticeTypeName != value))
			{
				this._NoticeTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailType", DbType="VarChar(10)")]
	public string MailType
	{
		get
		{
			return this._MailType;
		}
		set
		{
			if ((this._MailType != value))
			{
				this._MailType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTo", DbType="VarChar(1000)")]
	public string MailTo
	{
		get
		{
			return this._MailTo;
		}
		set
		{
			if ((this._MailTo != value))
			{
				this._MailTo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(200)")]
	public string Notes
	{
		get
		{
			return this._Notes;
		}
		set
		{
			if ((this._Notes != value))
			{
				this._Notes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this._Creator = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this._CreateDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this._ModifyDate = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_SysManager")]
public partial class List_SysManager : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _TableName;
	
	private string _UserID;
	
	private string _UserName;
	
	private string _TableRole;
	
	private string _TableID;
	
	private string _DeleteFlag;
	
	private string _DeleteBy;
	
	private System.Nullable<System.DateTime> _DeleteOn;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _AreaName;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTableNameChanging(string value);
    partial void OnTableNameChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTableRoleChanging(string value);
    partial void OnTableRoleChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnDeleteByChanging(string value);
    partial void OnDeleteByChanged();
    partial void OnDeleteOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteOnChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnAreaNameChanging(string value);
    partial void OnAreaNameChanged();
    #endregion
	
	public List_SysManager()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string TableName
	{
		get
		{
			return this._TableName;
		}
		set
		{
			if ((this._TableName != value))
			{
				this.OnTableNameChanging(value);
				this.SendPropertyChanging();
				this._TableName = value;
				this.SendPropertyChanged("TableName");
				this.OnTableNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableRole", DbType="VarChar(30)")]
	public string TableRole
	{
		get
		{
			return this._TableRole;
		}
		set
		{
			if ((this._TableRole != value))
			{
				this.OnTableRoleChanging(value);
				this.SendPropertyChanging();
				this._TableRole = value;
				this.SendPropertyChanged("TableRole");
				this.OnTableRoleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(30)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this.OnTableIDChanging(value);
				this.SendPropertyChanging();
				this._TableID = value;
				this.SendPropertyChanged("TableID");
				this.OnTableIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="VarChar(30)")]
	public string DeleteBy
	{
		get
		{
			return this._DeleteBy;
		}
		set
		{
			if ((this._DeleteBy != value))
			{
				this.OnDeleteByChanging(value);
				this.SendPropertyChanging();
				this._DeleteBy = value;
				this.SendPropertyChanged("DeleteBy");
				this.OnDeleteByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeleteOn
	{
		get
		{
			return this._DeleteOn;
		}
		set
		{
			if ((this._DeleteOn != value))
			{
				this.OnDeleteOnChanging(value);
				this.SendPropertyChanging();
				this._DeleteOn = value;
				this.SendPropertyChanged("DeleteOn");
				this.OnDeleteOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaName", DbType="VarChar(50)")]
	public string AreaName
	{
		get
		{
			return this._AreaName;
		}
		set
		{
			if ((this._AreaName != value))
			{
				this.OnAreaNameChanging(value);
				this.SendPropertyChanging();
				this._AreaName = value;
				this.SendPropertyChanged("AreaName");
				this.OnAreaNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormProjectBudget")]
public partial class FormProjectBudget : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _FormID;
	
	private string _FormNo;
	
	private string _FormType;
	
	private string _ApplyManNo;
	
	private string _ApplyMan;
	
	private System.Nullable<System.DateTime> _ApplyDate;
	
	private string _ApplyDept;
	
	private string _ApplyPhoneNo;
	
	private string _OUCode;
	
	private string _CompanyName;
	
	private string _FactoryArea;
	
	private string _ProjectCode;
	
	private string _StartCode;
	
	private string _EndCode;
	
	private string _YearCode;
	
	private string _ProjectType;
	
	private string _ProjectOwnerID;
	
	private string _ProjectOwnerName;
	
	private string _ProjectName;
	
	private string _Purpose;
	
	private System.Nullable<System.DateTime> _ProjectFinDate;
	
	private string _RFQNO;
	
	private string _IsBudget;
	
	private string _BudgetCurrency;
	
	private System.Nullable<double> _BudgetTotal;
	
	private string _BudgetDesc;
	
	private string _ProjectStatus;
	
	private string _ProjectStatusDesc;
	
	private string _BudgetReportDesc;
	
	private System.Nullable<double> _BudgetTotal_Final;
	
	private string _BudgetDesc_Add;
	
	private System.Nullable<int> _BudgetItem_Add;
	
	private string _CounterSign;
	
	private string _CounterSign_Hide;
	
	private string _DeleteFlag;
	
	private string _DeletedBy;
	
	private System.Nullable<System.DateTime> _DeletedOn;
	
	private string _DeletedReason;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	private string _SysID;
	
	private string _TableID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormIDChanging(int value);
    partial void OnFormIDChanged();
    partial void OnFormNoChanging(string value);
    partial void OnFormNoChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnApplyManNoChanging(string value);
    partial void OnApplyManNoChanged();
    partial void OnApplyManChanging(string value);
    partial void OnApplyManChanged();
    partial void OnApplyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnApplyDateChanged();
    partial void OnApplyDeptChanging(string value);
    partial void OnApplyDeptChanged();
    partial void OnApplyPhoneNoChanging(string value);
    partial void OnApplyPhoneNoChanged();
    partial void OnOUCodeChanging(string value);
    partial void OnOUCodeChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnFactoryAreaChanging(string value);
    partial void OnFactoryAreaChanged();
    partial void OnProjectCodeChanging(string value);
    partial void OnProjectCodeChanged();
    partial void OnStartCodeChanging(string value);
    partial void OnStartCodeChanged();
    partial void OnEndCodeChanging(string value);
    partial void OnEndCodeChanged();
    partial void OnYearCodeChanging(string value);
    partial void OnYearCodeChanged();
    partial void OnProjectTypeChanging(string value);
    partial void OnProjectTypeChanged();
    partial void OnProjectOwnerIDChanging(string value);
    partial void OnProjectOwnerIDChanged();
    partial void OnProjectOwnerNameChanging(string value);
    partial void OnProjectOwnerNameChanged();
    partial void OnProjectNameChanging(string value);
    partial void OnProjectNameChanged();
    partial void OnPurposeChanging(string value);
    partial void OnPurposeChanged();
    partial void OnProjectFinDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProjectFinDateChanged();
    partial void OnRFQNOChanging(string value);
    partial void OnRFQNOChanged();
    partial void OnIsBudgetChanging(string value);
    partial void OnIsBudgetChanged();
    partial void OnBudgetCurrencyChanging(string value);
    partial void OnBudgetCurrencyChanged();
    partial void OnBudgetTotalChanging(System.Nullable<double> value);
    partial void OnBudgetTotalChanged();
    partial void OnBudgetDescChanging(string value);
    partial void OnBudgetDescChanged();
    partial void OnProjectStatusChanging(string value);
    partial void OnProjectStatusChanged();
    partial void OnProjectStatusDescChanging(string value);
    partial void OnProjectStatusDescChanged();
    partial void OnBudgetReportDescChanging(string value);
    partial void OnBudgetReportDescChanged();
    partial void OnBudgetTotal_FinalChanging(System.Nullable<double> value);
    partial void OnBudgetTotal_FinalChanged();
    partial void OnBudgetDesc_AddChanging(string value);
    partial void OnBudgetDesc_AddChanged();
    partial void OnBudgetItem_AddChanging(System.Nullable<int> value);
    partial void OnBudgetItem_AddChanged();
    partial void OnCounterSignChanging(string value);
    partial void OnCounterSignChanged();
    partial void OnCounterSign_HideChanging(string value);
    partial void OnCounterSign_HideChanged();
    partial void OnDeleteFlagChanging(string value);
    partial void OnDeleteFlagChanged();
    partial void OnDeletedByChanging(string value);
    partial void OnDeletedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedReasonChanging(string value);
    partial void OnDeletedReasonChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnSysIDChanging(string value);
    partial void OnSysIDChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    #endregion
	
	public FormProjectBudget()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int FormID
	{
		get
		{
			return this._FormID;
		}
		set
		{
			if ((this._FormID != value))
			{
				this.OnFormIDChanging(value);
				this.SendPropertyChanging();
				this._FormID = value;
				this.SendPropertyChanged("FormID");
				this.OnFormIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNo", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string FormNo
	{
		get
		{
			return this._FormNo;
		}
		set
		{
			if ((this._FormNo != value))
			{
				this.OnFormNoChanging(value);
				this.SendPropertyChanging();
				this._FormNo = value;
				this.SendPropertyChanged("FormNo");
				this.OnFormNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(30)")]
	public string FormType
	{
		get
		{
			return this._FormType;
		}
		set
		{
			if ((this._FormType != value))
			{
				this.OnFormTypeChanging(value);
				this.SendPropertyChanging();
				this._FormType = value;
				this.SendPropertyChanged("FormType");
				this.OnFormTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyManNo", DbType="VarChar(10)")]
	public string ApplyManNo
	{
		get
		{
			return this._ApplyManNo;
		}
		set
		{
			if ((this._ApplyManNo != value))
			{
				this.OnApplyManNoChanging(value);
				this.SendPropertyChanging();
				this._ApplyManNo = value;
				this.SendPropertyChanged("ApplyManNo");
				this.OnApplyManNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyMan", DbType="VarChar(30)")]
	public string ApplyMan
	{
		get
		{
			return this._ApplyMan;
		}
		set
		{
			if ((this._ApplyMan != value))
			{
				this.OnApplyManChanging(value);
				this.SendPropertyChanging();
				this._ApplyMan = value;
				this.SendPropertyChanged("ApplyMan");
				this.OnApplyManChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ApplyDate
	{
		get
		{
			return this._ApplyDate;
		}
		set
		{
			if ((this._ApplyDate != value))
			{
				this.OnApplyDateChanging(value);
				this.SendPropertyChanging();
				this._ApplyDate = value;
				this.SendPropertyChanged("ApplyDate");
				this.OnApplyDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyDept", DbType="VarChar(50)")]
	public string ApplyDept
	{
		get
		{
			return this._ApplyDept;
		}
		set
		{
			if ((this._ApplyDept != value))
			{
				this.OnApplyDeptChanging(value);
				this.SendPropertyChanging();
				this._ApplyDept = value;
				this.SendPropertyChanged("ApplyDept");
				this.OnApplyDeptChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyPhoneNo", DbType="VarChar(50)")]
	public string ApplyPhoneNo
	{
		get
		{
			return this._ApplyPhoneNo;
		}
		set
		{
			if ((this._ApplyPhoneNo != value))
			{
				this.OnApplyPhoneNoChanging(value);
				this.SendPropertyChanging();
				this._ApplyPhoneNo = value;
				this.SendPropertyChanged("ApplyPhoneNo");
				this.OnApplyPhoneNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUCode", DbType="VarChar(10)")]
	public string OUCode
	{
		get
		{
			return this._OUCode;
		}
		set
		{
			if ((this._OUCode != value))
			{
				this.OnOUCodeChanging(value);
				this.SendPropertyChanging();
				this._OUCode = value;
				this.SendPropertyChanged("OUCode");
				this.OnOUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50)")]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this.OnCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._CompanyName = value;
				this.SendPropertyChanged("CompanyName");
				this.OnCompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryArea", DbType="VarChar(30)")]
	public string FactoryArea
	{
		get
		{
			return this._FactoryArea;
		}
		set
		{
			if ((this._FactoryArea != value))
			{
				this.OnFactoryAreaChanging(value);
				this.SendPropertyChanging();
				this._FactoryArea = value;
				this.SendPropertyChanged("FactoryArea");
				this.OnFactoryAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="VarChar(10)")]
	public string ProjectCode
	{
		get
		{
			return this._ProjectCode;
		}
		set
		{
			if ((this._ProjectCode != value))
			{
				this.OnProjectCodeChanging(value);
				this.SendPropertyChanging();
				this._ProjectCode = value;
				this.SendPropertyChanged("ProjectCode");
				this.OnProjectCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCode", DbType="VarChar(50)")]
	public string StartCode
	{
		get
		{
			return this._StartCode;
		}
		set
		{
			if ((this._StartCode != value))
			{
				this.OnStartCodeChanging(value);
				this.SendPropertyChanging();
				this._StartCode = value;
				this.SendPropertyChanged("StartCode");
				this.OnStartCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndCode", DbType="VarChar(50)")]
	public string EndCode
	{
		get
		{
			return this._EndCode;
		}
		set
		{
			if ((this._EndCode != value))
			{
				this.OnEndCodeChanging(value);
				this.SendPropertyChanging();
				this._EndCode = value;
				this.SendPropertyChanged("EndCode");
				this.OnEndCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearCode", DbType="VarChar(4)")]
	public string YearCode
	{
		get
		{
			return this._YearCode;
		}
		set
		{
			if ((this._YearCode != value))
			{
				this.OnYearCodeChanging(value);
				this.SendPropertyChanging();
				this._YearCode = value;
				this.SendPropertyChanged("YearCode");
				this.OnYearCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectType", DbType="NVarChar(100)")]
	public string ProjectType
	{
		get
		{
			return this._ProjectType;
		}
		set
		{
			if ((this._ProjectType != value))
			{
				this.OnProjectTypeChanging(value);
				this.SendPropertyChanging();
				this._ProjectType = value;
				this.SendPropertyChanged("ProjectType");
				this.OnProjectTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectOwnerID", DbType="VarChar(30)")]
	public string ProjectOwnerID
	{
		get
		{
			return this._ProjectOwnerID;
		}
		set
		{
			if ((this._ProjectOwnerID != value))
			{
				this.OnProjectOwnerIDChanging(value);
				this.SendPropertyChanging();
				this._ProjectOwnerID = value;
				this.SendPropertyChanged("ProjectOwnerID");
				this.OnProjectOwnerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectOwnerName", DbType="VarChar(30)")]
	public string ProjectOwnerName
	{
		get
		{
			return this._ProjectOwnerName;
		}
		set
		{
			if ((this._ProjectOwnerName != value))
			{
				this.OnProjectOwnerNameChanging(value);
				this.SendPropertyChanging();
				this._ProjectOwnerName = value;
				this.SendPropertyChanged("ProjectOwnerName");
				this.OnProjectOwnerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectName", DbType="NVarChar(100)")]
	public string ProjectName
	{
		get
		{
			return this._ProjectName;
		}
		set
		{
			if ((this._ProjectName != value))
			{
				this.OnProjectNameChanging(value);
				this.SendPropertyChanging();
				this._ProjectName = value;
				this.SendPropertyChanged("ProjectName");
				this.OnProjectNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
	public string Purpose
	{
		get
		{
			return this._Purpose;
		}
		set
		{
			if ((this._Purpose != value))
			{
				this.OnPurposeChanging(value);
				this.SendPropertyChanging();
				this._Purpose = value;
				this.SendPropertyChanged("Purpose");
				this.OnPurposeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectFinDate", DbType="Date")]
	public System.Nullable<System.DateTime> ProjectFinDate
	{
		get
		{
			return this._ProjectFinDate;
		}
		set
		{
			if ((this._ProjectFinDate != value))
			{
				this.OnProjectFinDateChanging(value);
				this.SendPropertyChanging();
				this._ProjectFinDate = value;
				this.SendPropertyChanged("ProjectFinDate");
				this.OnProjectFinDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFQNO", DbType="VarChar(30)")]
	public string RFQNO
	{
		get
		{
			return this._RFQNO;
		}
		set
		{
			if ((this._RFQNO != value))
			{
				this.OnRFQNOChanging(value);
				this.SendPropertyChanging();
				this._RFQNO = value;
				this.SendPropertyChanged("RFQNO");
				this.OnRFQNOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBudget", DbType="VarChar(1)")]
	public string IsBudget
	{
		get
		{
			return this._IsBudget;
		}
		set
		{
			if ((this._IsBudget != value))
			{
				this.OnIsBudgetChanging(value);
				this.SendPropertyChanging();
				this._IsBudget = value;
				this.SendPropertyChanged("IsBudget");
				this.OnIsBudgetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetCurrency", DbType="VarChar(6)")]
	public string BudgetCurrency
	{
		get
		{
			return this._BudgetCurrency;
		}
		set
		{
			if ((this._BudgetCurrency != value))
			{
				this.OnBudgetCurrencyChanging(value);
				this.SendPropertyChanging();
				this._BudgetCurrency = value;
				this.SendPropertyChanged("BudgetCurrency");
				this.OnBudgetCurrencyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTotal", DbType="Float")]
	public System.Nullable<double> BudgetTotal
	{
		get
		{
			return this._BudgetTotal;
		}
		set
		{
			if ((this._BudgetTotal != value))
			{
				this.OnBudgetTotalChanging(value);
				this.SendPropertyChanging();
				this._BudgetTotal = value;
				this.SendPropertyChanged("BudgetTotal");
				this.OnBudgetTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetDesc", DbType="VarChar(500)")]
	public string BudgetDesc
	{
		get
		{
			return this._BudgetDesc;
		}
		set
		{
			if ((this._BudgetDesc != value))
			{
				this.OnBudgetDescChanging(value);
				this.SendPropertyChanging();
				this._BudgetDesc = value;
				this.SendPropertyChanged("BudgetDesc");
				this.OnBudgetDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectStatus", DbType="VarChar(10)")]
	public string ProjectStatus
	{
		get
		{
			return this._ProjectStatus;
		}
		set
		{
			if ((this._ProjectStatus != value))
			{
				this.OnProjectStatusChanging(value);
				this.SendPropertyChanging();
				this._ProjectStatus = value;
				this.SendPropertyChanged("ProjectStatus");
				this.OnProjectStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectStatusDesc", DbType="NVarChar(500)")]
	public string ProjectStatusDesc
	{
		get
		{
			return this._ProjectStatusDesc;
		}
		set
		{
			if ((this._ProjectStatusDesc != value))
			{
				this.OnProjectStatusDescChanging(value);
				this.SendPropertyChanging();
				this._ProjectStatusDesc = value;
				this.SendPropertyChanged("ProjectStatusDesc");
				this.OnProjectStatusDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetReportDesc", DbType="NVarChar(500)")]
	public string BudgetReportDesc
	{
		get
		{
			return this._BudgetReportDesc;
		}
		set
		{
			if ((this._BudgetReportDesc != value))
			{
				this.OnBudgetReportDescChanging(value);
				this.SendPropertyChanging();
				this._BudgetReportDesc = value;
				this.SendPropertyChanged("BudgetReportDesc");
				this.OnBudgetReportDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTotal_Final", DbType="Float")]
	public System.Nullable<double> BudgetTotal_Final
	{
		get
		{
			return this._BudgetTotal_Final;
		}
		set
		{
			if ((this._BudgetTotal_Final != value))
			{
				this.OnBudgetTotal_FinalChanging(value);
				this.SendPropertyChanging();
				this._BudgetTotal_Final = value;
				this.SendPropertyChanged("BudgetTotal_Final");
				this.OnBudgetTotal_FinalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetDesc_Add", DbType="VarChar(500)")]
	public string BudgetDesc_Add
	{
		get
		{
			return this._BudgetDesc_Add;
		}
		set
		{
			if ((this._BudgetDesc_Add != value))
			{
				this.OnBudgetDesc_AddChanging(value);
				this.SendPropertyChanging();
				this._BudgetDesc_Add = value;
				this.SendPropertyChanged("BudgetDesc_Add");
				this.OnBudgetDesc_AddChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetItem_Add", DbType="Int")]
	public System.Nullable<int> BudgetItem_Add
	{
		get
		{
			return this._BudgetItem_Add;
		}
		set
		{
			if ((this._BudgetItem_Add != value))
			{
				this.OnBudgetItem_AddChanging(value);
				this.SendPropertyChanging();
				this._BudgetItem_Add = value;
				this.SendPropertyChanged("BudgetItem_Add");
				this.OnBudgetItem_AddChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterSign", DbType="VarChar(100)")]
	public string CounterSign
	{
		get
		{
			return this._CounterSign;
		}
		set
		{
			if ((this._CounterSign != value))
			{
				this.OnCounterSignChanging(value);
				this.SendPropertyChanging();
				this._CounterSign = value;
				this.SendPropertyChanged("CounterSign");
				this.OnCounterSignChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterSign_Hide", DbType="VarChar(100)")]
	public string CounterSign_Hide
	{
		get
		{
			return this._CounterSign_Hide;
		}
		set
		{
			if ((this._CounterSign_Hide != value))
			{
				this.OnCounterSign_HideChanging(value);
				this.SendPropertyChanging();
				this._CounterSign_Hide = value;
				this.SendPropertyChanged("CounterSign_Hide");
				this.OnCounterSign_HideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="VarChar(1)")]
	public string DeleteFlag
	{
		get
		{
			return this._DeleteFlag;
		}
		set
		{
			if ((this._DeleteFlag != value))
			{
				this.OnDeleteFlagChanging(value);
				this.SendPropertyChanging();
				this._DeleteFlag = value;
				this.SendPropertyChanged("DeleteFlag");
				this.OnDeleteFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="VarChar(30)")]
	public string DeletedBy
	{
		get
		{
			return this._DeletedBy;
		}
		set
		{
			if ((this._DeletedBy != value))
			{
				this.OnDeletedByChanging(value);
				this.SendPropertyChanging();
				this._DeletedBy = value;
				this.SendPropertyChanged("DeletedBy");
				this.OnDeletedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeletedOn
	{
		get
		{
			return this._DeletedOn;
		}
		set
		{
			if ((this._DeletedOn != value))
			{
				this.OnDeletedOnChanging(value);
				this.SendPropertyChanging();
				this._DeletedOn = value;
				this.SendPropertyChanged("DeletedOn");
				this.OnDeletedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedReason", DbType="VarChar(100)")]
	public string DeletedReason
	{
		get
		{
			return this._DeletedReason;
		}
		set
		{
			if ((this._DeletedReason != value))
			{
				this.OnDeletedReasonChanging(value);
				this.SendPropertyChanging();
				this._DeletedReason = value;
				this.SendPropertyChanged("DeletedReason");
				this.OnDeletedReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysID", DbType="VarChar(10)")]
	public string SysID
	{
		get
		{
			return this._SysID;
		}
		set
		{
			if ((this._SysID != value))
			{
				this.OnSysIDChanging(value);
				this.SendPropertyChanging();
				this._SysID = value;
				this.SendPropertyChanged("SysID");
				this.OnSysIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="VarChar(10)")]
	public string TableID
	{
		get
		{
			return this._TableID;
		}
		set
		{
			if ((this._TableID != value))
			{
				this.OnTableIDChanging(value);
				this.SendPropertyChanging();
				this._TableID = value;
				this.SendPropertyChanged("TableID");
				this.OnTableIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
