#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR_Employee")]
public partial class HRDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertFormEmployee(FormEmployee instance);
  partial void UpdateFormEmployee(FormEmployee instance);
  partial void DeleteFormEmployee(FormEmployee instance);
  partial void InsertFormCapacity(FormCapacity instance);
  partial void UpdateFormCapacity(FormCapacity instance);
  partial void DeleteFormCapacity(FormCapacity instance);
  #endregion
	
	public HRDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HR_EmployeeConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HRDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HRDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<V_EmpForGeneral> V_EmpForGeneral
	{
		get
		{
			return this.GetTable<V_EmpForGeneral>();
		}
	}
	
	public System.Data.Linq.Table<FormEmployee> FormEmployee
	{
		get
		{
			return this.GetTable<FormEmployee>();
		}
	}
	
	public System.Data.Linq.Table<FormCapacity> FormCapacity
	{
		get
		{
			return this.GetTable<FormCapacity>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EmpForGeneral")]
public partial class V_EmpForGeneral
{
	
	private string _UserNo;
	
	private string _UserChiname;
	
	private string _Location;
	
	private string _CompanyName;
	
	private string _Department;
	
	private string _SectionLevel;
	
	private string _DeputyLevel;
	
	private string _DirectorLevel;
	
	private string _OUCode;
	
	private string _JobTitle;
	
	private string _PhoneNo;
	
	private string _InternetAddress;
	
	private string _SuperiorNo;
	
	private string _SuperiorCharge;
	
	private string _Agent_1;
	
	private string _Agent_2;
	
	private string _Agent_3;
	
	private string _JobType;
	
	public V_EmpForGeneral()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string UserNo
	{
		get
		{
			return this._UserNo;
		}
		set
		{
			if ((this._UserNo != value))
			{
				this._UserNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserChiname", DbType="VarChar(30)")]
	public string UserChiname
	{
		get
		{
			return this._UserChiname;
		}
		set
		{
			if ((this._UserChiname != value))
			{
				this._UserChiname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(30)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this._Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50)")]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this._CompanyName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(100)")]
	public string Department
	{
		get
		{
			return this._Department;
		}
		set
		{
			if ((this._Department != value))
			{
				this._Department = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionLevel", DbType="VarChar(50)")]
	public string SectionLevel
	{
		get
		{
			return this._SectionLevel;
		}
		set
		{
			if ((this._SectionLevel != value))
			{
				this._SectionLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeputyLevel", DbType="VarChar(50)")]
	public string DeputyLevel
	{
		get
		{
			return this._DeputyLevel;
		}
		set
		{
			if ((this._DeputyLevel != value))
			{
				this._DeputyLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectorLevel", DbType="VarChar(50)")]
	public string DirectorLevel
	{
		get
		{
			return this._DirectorLevel;
		}
		set
		{
			if ((this._DirectorLevel != value))
			{
				this._DirectorLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUCode", DbType="VarChar(10)")]
	public string OUCode
	{
		get
		{
			return this._OUCode;
		}
		set
		{
			if ((this._OUCode != value))
			{
				this._OUCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(100)")]
	public string JobTitle
	{
		get
		{
			return this._JobTitle;
		}
		set
		{
			if ((this._JobTitle != value))
			{
				this._JobTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
	public string PhoneNo
	{
		get
		{
			return this._PhoneNo;
		}
		set
		{
			if ((this._PhoneNo != value))
			{
				this._PhoneNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternetAddress", DbType="VarChar(50)")]
	public string InternetAddress
	{
		get
		{
			return this._InternetAddress;
		}
		set
		{
			if ((this._InternetAddress != value))
			{
				this._InternetAddress = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorNo", DbType="VarChar(50)")]
	public string SuperiorNo
	{
		get
		{
			return this._SuperiorNo;
		}
		set
		{
			if ((this._SuperiorNo != value))
			{
				this._SuperiorNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorCharge", DbType="VarChar(100)")]
	public string SuperiorCharge
	{
		get
		{
			return this._SuperiorCharge;
		}
		set
		{
			if ((this._SuperiorCharge != value))
			{
				this._SuperiorCharge = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_1", DbType="VarChar(30)")]
	public string Agent_1
	{
		get
		{
			return this._Agent_1;
		}
		set
		{
			if ((this._Agent_1 != value))
			{
				this._Agent_1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_2", DbType="VarChar(30)")]
	public string Agent_2
	{
		get
		{
			return this._Agent_2;
		}
		set
		{
			if ((this._Agent_2 != value))
			{
				this._Agent_2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_3", DbType="VarChar(30)")]
	public string Agent_3
	{
		get
		{
			return this._Agent_3;
		}
		set
		{
			if ((this._Agent_3 != value))
			{
				this._Agent_3 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobType", DbType="VarChar(30)")]
	public string JobType
	{
		get
		{
			return this._JobType;
		}
		set
		{
			if ((this._JobType != value))
			{
				this._JobType = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormEmployee")]
public partial class FormEmployee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _DocID;
	
	private string _UserNo;
	
	private string _UserChiname;
	
	private string _UserEngName;
	
	private string _Sex;
	
	private System.Nullable<System.DateTime> _Birthday;
	
	private string _IDCardNo;
	
	private string _GroupType;
	
	private string _CompanyName;
	
	private string _Department;
	
	private System.Nullable<int> _DeptLevel;
	
	private string _OUCode;
	
	private string _UpperOU;
	
	private string _UpperOUCode;
	
	private string _NotesID;
	
	private string _NotesCN;
	
	private string _SuperiorNo;
	
	private string _SuperiorChargeID;
	
	private string _SuperiorCharge;
	
	private System.Nullable<System.DateTime> _RegisterDate;
	
	private string _JobTitle;
	
	private System.Nullable<int> _JobLevel;
	
	private string _Location;
	
	private string _PhoneNo;
	
	private string _JobType;
	
	private string _AgentAction;
	
	private string _FormalStaff;
	
	private string _IsOULeader;
	
	private System.Nullable<System.DateTime> _LeaveJobDate;
	
	private string _LeaveJob;
	
	private string _LeaveJobType;
	
	private string _InternetAddress;
	
	private string _Agent_1;
	
	private string _Agent_2;
	
	private string _Agent_3;
	
	private string _NAgent_1;
	
	private string _NAgent_2;
	
	private string _NAgent_3;
	
	private string _Creator;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
	private string _UpperOUPath;
	
	private string _SectionLevel;
	
	private string _DeputyLevel;
	
	private string _DirectorLevel;
	
	private string _Capacity;
	
	private string _RegisterAdd;
	
	private string _MessageAdd;
	
	private string _InstancyName;
	
	private string _InstancyAdd;
	
	private string _InstancyTel;
	
	private string _IsNotMarry;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocIDChanging(string value);
    partial void OnDocIDChanged();
    partial void OnUserNoChanging(string value);
    partial void OnUserNoChanged();
    partial void OnUserChinameChanging(string value);
    partial void OnUserChinameChanged();
    partial void OnUserEngNameChanging(string value);
    partial void OnUserEngNameChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnIDCardNoChanging(string value);
    partial void OnIDCardNoChanged();
    partial void OnGroupTypeChanging(string value);
    partial void OnGroupTypeChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnDeptLevelChanging(System.Nullable<int> value);
    partial void OnDeptLevelChanged();
    partial void OnOUCodeChanging(string value);
    partial void OnOUCodeChanged();
    partial void OnUpperOUChanging(string value);
    partial void OnUpperOUChanged();
    partial void OnUpperOUCodeChanging(string value);
    partial void OnUpperOUCodeChanged();
    partial void OnNotesIDChanging(string value);
    partial void OnNotesIDChanged();
    partial void OnNotesCNChanging(string value);
    partial void OnNotesCNChanged();
    partial void OnSuperiorNoChanging(string value);
    partial void OnSuperiorNoChanged();
    partial void OnSuperiorChargeIDChanging(string value);
    partial void OnSuperiorChargeIDChanged();
    partial void OnSuperiorChargeChanging(string value);
    partial void OnSuperiorChargeChanged();
    partial void OnRegisterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegisterDateChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnJobLevelChanging(System.Nullable<int> value);
    partial void OnJobLevelChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnJobTypeChanging(string value);
    partial void OnJobTypeChanged();
    partial void OnAgentActionChanging(string value);
    partial void OnAgentActionChanged();
    partial void OnFormalStaffChanging(string value);
    partial void OnFormalStaffChanged();
    partial void OnIsOULeaderChanging(string value);
    partial void OnIsOULeaderChanged();
    partial void OnLeaveJobDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLeaveJobDateChanged();
    partial void OnLeaveJobChanging(string value);
    partial void OnLeaveJobChanged();
    partial void OnLeaveJobTypeChanging(string value);
    partial void OnLeaveJobTypeChanged();
    partial void OnInternetAddressChanging(string value);
    partial void OnInternetAddressChanged();
    partial void OnAgent_1Changing(string value);
    partial void OnAgent_1Changed();
    partial void OnAgent_2Changing(string value);
    partial void OnAgent_2Changed();
    partial void OnAgent_3Changing(string value);
    partial void OnAgent_3Changed();
    partial void OnNAgent_1Changing(string value);
    partial void OnNAgent_1Changed();
    partial void OnNAgent_2Changing(string value);
    partial void OnNAgent_2Changed();
    partial void OnNAgent_3Changing(string value);
    partial void OnNAgent_3Changed();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnUpperOUPathChanging(string value);
    partial void OnUpperOUPathChanged();
    partial void OnSectionLevelChanging(string value);
    partial void OnSectionLevelChanged();
    partial void OnDeputyLevelChanging(string value);
    partial void OnDeputyLevelChanged();
    partial void OnDirectorLevelChanging(string value);
    partial void OnDirectorLevelChanged();
    partial void OnCapacityChanging(string value);
    partial void OnCapacityChanged();
    partial void OnRegisterAddChanging(string value);
    partial void OnRegisterAddChanged();
    partial void OnMessageAddChanging(string value);
    partial void OnMessageAddChanged();
    partial void OnInstancyNameChanging(string value);
    partial void OnInstancyNameChanged();
    partial void OnInstancyAddChanging(string value);
    partial void OnInstancyAddChanged();
    partial void OnInstancyTelChanging(string value);
    partial void OnInstancyTelChanged();
    partial void OnIsNotMarryChanging(string value);
    partial void OnIsNotMarryChanged();
    #endregion
	
	public FormEmployee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocID", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string DocID
	{
		get
		{
			return this._DocID;
		}
		set
		{
			if ((this._DocID != value))
			{
				this.OnDocIDChanging(value);
				this.SendPropertyChanging();
				this._DocID = value;
				this.SendPropertyChanged("DocID");
				this.OnDocIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UserNo
	{
		get
		{
			return this._UserNo;
		}
		set
		{
			if ((this._UserNo != value))
			{
				this.OnUserNoChanging(value);
				this.SendPropertyChanging();
				this._UserNo = value;
				this.SendPropertyChanged("UserNo");
				this.OnUserNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserChiname", DbType="VarChar(30)")]
	public string UserChiname
	{
		get
		{
			return this._UserChiname;
		}
		set
		{
			if ((this._UserChiname != value))
			{
				this.OnUserChinameChanging(value);
				this.SendPropertyChanging();
				this._UserChiname = value;
				this.SendPropertyChanged("UserChiname");
				this.OnUserChinameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEngName", DbType="VarChar(30)")]
	public string UserEngName
	{
		get
		{
			return this._UserEngName;
		}
		set
		{
			if ((this._UserEngName != value))
			{
				this.OnUserEngNameChanging(value);
				this.SendPropertyChanging();
				this._UserEngName = value;
				this.SendPropertyChanged("UserEngName");
				this.OnUserEngNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(2)")]
	public string Sex
	{
		get
		{
			return this._Sex;
		}
		set
		{
			if ((this._Sex != value))
			{
				this.OnSexChanging(value);
				this.SendPropertyChanging();
				this._Sex = value;
				this.SendPropertyChanged("Sex");
				this.OnSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="Date")]
	public System.Nullable<System.DateTime> Birthday
	{
		get
		{
			return this._Birthday;
		}
		set
		{
			if ((this._Birthday != value))
			{
				this.OnBirthdayChanging(value);
				this.SendPropertyChanging();
				this._Birthday = value;
				this.SendPropertyChanged("Birthday");
				this.OnBirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCardNo", DbType="VarChar(20)")]
	public string IDCardNo
	{
		get
		{
			return this._IDCardNo;
		}
		set
		{
			if ((this._IDCardNo != value))
			{
				this.OnIDCardNoChanging(value);
				this.SendPropertyChanging();
				this._IDCardNo = value;
				this.SendPropertyChanged("IDCardNo");
				this.OnIDCardNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupType", DbType="VarChar(30)")]
	public string GroupType
	{
		get
		{
			return this._GroupType;
		}
		set
		{
			if ((this._GroupType != value))
			{
				this.OnGroupTypeChanging(value);
				this.SendPropertyChanging();
				this._GroupType = value;
				this.SendPropertyChanged("GroupType");
				this.OnGroupTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50)")]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this.OnCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._CompanyName = value;
				this.SendPropertyChanged("CompanyName");
				this.OnCompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(100)")]
	public string Department
	{
		get
		{
			return this._Department;
		}
		set
		{
			if ((this._Department != value))
			{
				this.OnDepartmentChanging(value);
				this.SendPropertyChanging();
				this._Department = value;
				this.SendPropertyChanged("Department");
				this.OnDepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptLevel", DbType="Int")]
	public System.Nullable<int> DeptLevel
	{
		get
		{
			return this._DeptLevel;
		}
		set
		{
			if ((this._DeptLevel != value))
			{
				this.OnDeptLevelChanging(value);
				this.SendPropertyChanging();
				this._DeptLevel = value;
				this.SendPropertyChanged("DeptLevel");
				this.OnDeptLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUCode", DbType="VarChar(10)")]
	public string OUCode
	{
		get
		{
			return this._OUCode;
		}
		set
		{
			if ((this._OUCode != value))
			{
				this.OnOUCodeChanging(value);
				this.SendPropertyChanging();
				this._OUCode = value;
				this.SendPropertyChanged("OUCode");
				this.OnOUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpperOU", DbType="VarChar(50)")]
	public string UpperOU
	{
		get
		{
			return this._UpperOU;
		}
		set
		{
			if ((this._UpperOU != value))
			{
				this.OnUpperOUChanging(value);
				this.SendPropertyChanging();
				this._UpperOU = value;
				this.SendPropertyChanged("UpperOU");
				this.OnUpperOUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpperOUCode", DbType="VarChar(10)")]
	public string UpperOUCode
	{
		get
		{
			return this._UpperOUCode;
		}
		set
		{
			if ((this._UpperOUCode != value))
			{
				this.OnUpperOUCodeChanging(value);
				this.SendPropertyChanging();
				this._UpperOUCode = value;
				this.SendPropertyChanged("UpperOUCode");
				this.OnUpperOUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotesID", DbType="VarChar(50)")]
	public string NotesID
	{
		get
		{
			return this._NotesID;
		}
		set
		{
			if ((this._NotesID != value))
			{
				this.OnNotesIDChanging(value);
				this.SendPropertyChanging();
				this._NotesID = value;
				this.SendPropertyChanged("NotesID");
				this.OnNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotesCN", DbType="VarChar(30)")]
	public string NotesCN
	{
		get
		{
			return this._NotesCN;
		}
		set
		{
			if ((this._NotesCN != value))
			{
				this.OnNotesCNChanging(value);
				this.SendPropertyChanging();
				this._NotesCN = value;
				this.SendPropertyChanged("NotesCN");
				this.OnNotesCNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorNo", DbType="VarChar(50)")]
	public string SuperiorNo
	{
		get
		{
			return this._SuperiorNo;
		}
		set
		{
			if ((this._SuperiorNo != value))
			{
				this.OnSuperiorNoChanging(value);
				this.SendPropertyChanging();
				this._SuperiorNo = value;
				this.SendPropertyChanged("SuperiorNo");
				this.OnSuperiorNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorChargeID", DbType="VarChar(100)")]
	public string SuperiorChargeID
	{
		get
		{
			return this._SuperiorChargeID;
		}
		set
		{
			if ((this._SuperiorChargeID != value))
			{
				this.OnSuperiorChargeIDChanging(value);
				this.SendPropertyChanging();
				this._SuperiorChargeID = value;
				this.SendPropertyChanged("SuperiorChargeID");
				this.OnSuperiorChargeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorCharge", DbType="VarChar(100)")]
	public string SuperiorCharge
	{
		get
		{
			return this._SuperiorCharge;
		}
		set
		{
			if ((this._SuperiorCharge != value))
			{
				this.OnSuperiorChargeChanging(value);
				this.SendPropertyChanging();
				this._SuperiorCharge = value;
				this.SendPropertyChanged("SuperiorCharge");
				this.OnSuperiorChargeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterDate", DbType="Date")]
	public System.Nullable<System.DateTime> RegisterDate
	{
		get
		{
			return this._RegisterDate;
		}
		set
		{
			if ((this._RegisterDate != value))
			{
				this.OnRegisterDateChanging(value);
				this.SendPropertyChanging();
				this._RegisterDate = value;
				this.SendPropertyChanged("RegisterDate");
				this.OnRegisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(100)")]
	public string JobTitle
	{
		get
		{
			return this._JobTitle;
		}
		set
		{
			if ((this._JobTitle != value))
			{
				this.OnJobTitleChanging(value);
				this.SendPropertyChanging();
				this._JobTitle = value;
				this.SendPropertyChanged("JobTitle");
				this.OnJobTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobLevel", DbType="Int")]
	public System.Nullable<int> JobLevel
	{
		get
		{
			return this._JobLevel;
		}
		set
		{
			if ((this._JobLevel != value))
			{
				this.OnJobLevelChanging(value);
				this.SendPropertyChanging();
				this._JobLevel = value;
				this.SendPropertyChanged("JobLevel");
				this.OnJobLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(30)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
	public string PhoneNo
	{
		get
		{
			return this._PhoneNo;
		}
		set
		{
			if ((this._PhoneNo != value))
			{
				this.OnPhoneNoChanging(value);
				this.SendPropertyChanging();
				this._PhoneNo = value;
				this.SendPropertyChanged("PhoneNo");
				this.OnPhoneNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobType", DbType="VarChar(30)")]
	public string JobType
	{
		get
		{
			return this._JobType;
		}
		set
		{
			if ((this._JobType != value))
			{
				this.OnJobTypeChanging(value);
				this.SendPropertyChanging();
				this._JobType = value;
				this.SendPropertyChanged("JobType");
				this.OnJobTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentAction", DbType="VarChar(1)")]
	public string AgentAction
	{
		get
		{
			return this._AgentAction;
		}
		set
		{
			if ((this._AgentAction != value))
			{
				this.OnAgentActionChanging(value);
				this.SendPropertyChanging();
				this._AgentAction = value;
				this.SendPropertyChanged("AgentAction");
				this.OnAgentActionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormalStaff", DbType="VarChar(1)")]
	public string FormalStaff
	{
		get
		{
			return this._FormalStaff;
		}
		set
		{
			if ((this._FormalStaff != value))
			{
				this.OnFormalStaffChanging(value);
				this.SendPropertyChanging();
				this._FormalStaff = value;
				this.SendPropertyChanged("FormalStaff");
				this.OnFormalStaffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOULeader", DbType="VarChar(1)")]
	public string IsOULeader
	{
		get
		{
			return this._IsOULeader;
		}
		set
		{
			if ((this._IsOULeader != value))
			{
				this.OnIsOULeaderChanging(value);
				this.SendPropertyChanging();
				this._IsOULeader = value;
				this.SendPropertyChanged("IsOULeader");
				this.OnIsOULeaderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveJobDate", DbType="Date")]
	public System.Nullable<System.DateTime> LeaveJobDate
	{
		get
		{
			return this._LeaveJobDate;
		}
		set
		{
			if ((this._LeaveJobDate != value))
			{
				this.OnLeaveJobDateChanging(value);
				this.SendPropertyChanging();
				this._LeaveJobDate = value;
				this.SendPropertyChanged("LeaveJobDate");
				this.OnLeaveJobDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveJob", DbType="VarChar(1)")]
	public string LeaveJob
	{
		get
		{
			return this._LeaveJob;
		}
		set
		{
			if ((this._LeaveJob != value))
			{
				this.OnLeaveJobChanging(value);
				this.SendPropertyChanging();
				this._LeaveJob = value;
				this.SendPropertyChanged("LeaveJob");
				this.OnLeaveJobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveJobType", DbType="VarChar(50)")]
	public string LeaveJobType
	{
		get
		{
			return this._LeaveJobType;
		}
		set
		{
			if ((this._LeaveJobType != value))
			{
				this.OnLeaveJobTypeChanging(value);
				this.SendPropertyChanging();
				this._LeaveJobType = value;
				this.SendPropertyChanged("LeaveJobType");
				this.OnLeaveJobTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternetAddress", DbType="VarChar(50)")]
	public string InternetAddress
	{
		get
		{
			return this._InternetAddress;
		}
		set
		{
			if ((this._InternetAddress != value))
			{
				this.OnInternetAddressChanging(value);
				this.SendPropertyChanging();
				this._InternetAddress = value;
				this.SendPropertyChanged("InternetAddress");
				this.OnInternetAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_1", DbType="VarChar(30)")]
	public string Agent_1
	{
		get
		{
			return this._Agent_1;
		}
		set
		{
			if ((this._Agent_1 != value))
			{
				this.OnAgent_1Changing(value);
				this.SendPropertyChanging();
				this._Agent_1 = value;
				this.SendPropertyChanged("Agent_1");
				this.OnAgent_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_2", DbType="VarChar(30)")]
	public string Agent_2
	{
		get
		{
			return this._Agent_2;
		}
		set
		{
			if ((this._Agent_2 != value))
			{
				this.OnAgent_2Changing(value);
				this.SendPropertyChanging();
				this._Agent_2 = value;
				this.SendPropertyChanged("Agent_2");
				this.OnAgent_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_3", DbType="VarChar(30)")]
	public string Agent_3
	{
		get
		{
			return this._Agent_3;
		}
		set
		{
			if ((this._Agent_3 != value))
			{
				this.OnAgent_3Changing(value);
				this.SendPropertyChanging();
				this._Agent_3 = value;
				this.SendPropertyChanged("Agent_3");
				this.OnAgent_3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAgent_1", DbType="VarChar(30)")]
	public string NAgent_1
	{
		get
		{
			return this._NAgent_1;
		}
		set
		{
			if ((this._NAgent_1 != value))
			{
				this.OnNAgent_1Changing(value);
				this.SendPropertyChanging();
				this._NAgent_1 = value;
				this.SendPropertyChanged("NAgent_1");
				this.OnNAgent_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAgent_2", DbType="VarChar(30)")]
	public string NAgent_2
	{
		get
		{
			return this._NAgent_2;
		}
		set
		{
			if ((this._NAgent_2 != value))
			{
				this.OnNAgent_2Changing(value);
				this.SendPropertyChanging();
				this._NAgent_2 = value;
				this.SendPropertyChanged("NAgent_2");
				this.OnNAgent_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAgent_3", DbType="VarChar(30)")]
	public string NAgent_3
	{
		get
		{
			return this._NAgent_3;
		}
		set
		{
			if ((this._NAgent_3 != value))
			{
				this.OnNAgent_3Changing(value);
				this.SendPropertyChanging();
				this._NAgent_3 = value;
				this.SendPropertyChanged("NAgent_3");
				this.OnNAgent_3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(30)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpperOUPath", DbType="VarChar(500)")]
	public string UpperOUPath
	{
		get
		{
			return this._UpperOUPath;
		}
		set
		{
			if ((this._UpperOUPath != value))
			{
				this.OnUpperOUPathChanging(value);
				this.SendPropertyChanging();
				this._UpperOUPath = value;
				this.SendPropertyChanged("UpperOUPath");
				this.OnUpperOUPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionLevel", DbType="VarChar(50)")]
	public string SectionLevel
	{
		get
		{
			return this._SectionLevel;
		}
		set
		{
			if ((this._SectionLevel != value))
			{
				this.OnSectionLevelChanging(value);
				this.SendPropertyChanging();
				this._SectionLevel = value;
				this.SendPropertyChanged("SectionLevel");
				this.OnSectionLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeputyLevel", DbType="VarChar(50)")]
	public string DeputyLevel
	{
		get
		{
			return this._DeputyLevel;
		}
		set
		{
			if ((this._DeputyLevel != value))
			{
				this.OnDeputyLevelChanging(value);
				this.SendPropertyChanging();
				this._DeputyLevel = value;
				this.SendPropertyChanged("DeputyLevel");
				this.OnDeputyLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectorLevel", DbType="VarChar(50)")]
	public string DirectorLevel
	{
		get
		{
			return this._DirectorLevel;
		}
		set
		{
			if ((this._DirectorLevel != value))
			{
				this.OnDirectorLevelChanging(value);
				this.SendPropertyChanging();
				this._DirectorLevel = value;
				this.SendPropertyChanged("DirectorLevel");
				this.OnDirectorLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="VarChar(30)")]
	public string Capacity
	{
		get
		{
			return this._Capacity;
		}
		set
		{
			if ((this._Capacity != value))
			{
				this.OnCapacityChanging(value);
				this.SendPropertyChanging();
				this._Capacity = value;
				this.SendPropertyChanged("Capacity");
				this.OnCapacityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterAdd", DbType="VarChar(90)")]
	public string RegisterAdd
	{
		get
		{
			return this._RegisterAdd;
		}
		set
		{
			if ((this._RegisterAdd != value))
			{
				this.OnRegisterAddChanging(value);
				this.SendPropertyChanging();
				this._RegisterAdd = value;
				this.SendPropertyChanged("RegisterAdd");
				this.OnRegisterAddChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageAdd", DbType="VarChar(90)")]
	public string MessageAdd
	{
		get
		{
			return this._MessageAdd;
		}
		set
		{
			if ((this._MessageAdd != value))
			{
				this.OnMessageAddChanging(value);
				this.SendPropertyChanging();
				this._MessageAdd = value;
				this.SendPropertyChanged("MessageAdd");
				this.OnMessageAddChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstancyName", DbType="VarChar(30)")]
	public string InstancyName
	{
		get
		{
			return this._InstancyName;
		}
		set
		{
			if ((this._InstancyName != value))
			{
				this.OnInstancyNameChanging(value);
				this.SendPropertyChanging();
				this._InstancyName = value;
				this.SendPropertyChanged("InstancyName");
				this.OnInstancyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstancyAdd", DbType="VarChar(90)")]
	public string InstancyAdd
	{
		get
		{
			return this._InstancyAdd;
		}
		set
		{
			if ((this._InstancyAdd != value))
			{
				this.OnInstancyAddChanging(value);
				this.SendPropertyChanging();
				this._InstancyAdd = value;
				this.SendPropertyChanged("InstancyAdd");
				this.OnInstancyAddChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstancyTel", DbType="VarChar(50)")]
	public string InstancyTel
	{
		get
		{
			return this._InstancyTel;
		}
		set
		{
			if ((this._InstancyTel != value))
			{
				this.OnInstancyTelChanging(value);
				this.SendPropertyChanging();
				this._InstancyTel = value;
				this.SendPropertyChanged("InstancyTel");
				this.OnInstancyTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNotMarry", DbType="VarChar(1)")]
	public string IsNotMarry
	{
		get
		{
			return this._IsNotMarry;
		}
		set
		{
			if ((this._IsNotMarry != value))
			{
				this.OnIsNotMarryChanging(value);
				this.SendPropertyChanging();
				this._IsNotMarry = value;
				this.SendPropertyChanged("IsNotMarry");
				this.OnIsNotMarryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormCapacity")]
public partial class FormCapacity : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CapacityID;
	
	private string _CapacityName;
	
	private System.Nullable<int> _AccountJobID;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private System.Nullable<System.DateTime> _ModifyDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacityIDChanging(int value);
    partial void OnCapacityIDChanged();
    partial void OnCapacityNameChanging(string value);
    partial void OnCapacityNameChanged();
    partial void OnAccountJobIDChanging(System.Nullable<int> value);
    partial void OnAccountJobIDChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    #endregion
	
	public FormCapacity()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacityID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CapacityID
	{
		get
		{
			return this._CapacityID;
		}
		set
		{
			if ((this._CapacityID != value))
			{
				this.OnCapacityIDChanging(value);
				this.SendPropertyChanging();
				this._CapacityID = value;
				this.SendPropertyChanged("CapacityID");
				this.OnCapacityIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacityName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string CapacityName
	{
		get
		{
			return this._CapacityName;
		}
		set
		{
			if ((this._CapacityName != value))
			{
				this.OnCapacityNameChanging(value);
				this.SendPropertyChanging();
				this._CapacityName = value;
				this.SendPropertyChanged("CapacityName");
				this.OnCapacityNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountJobID", DbType="Int")]
	public System.Nullable<int> AccountJobID
	{
		get
		{
			return this._AccountJobID;
		}
		set
		{
			if ((this._AccountJobID != value))
			{
				this.OnAccountJobIDChanging(value);
				this.SendPropertyChanging();
				this._AccountJobID = value;
				this.SendPropertyChanged("AccountJobID");
				this.OnAccountJobIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
