#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BASE_DATA")]
public partial class HR_LoginDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertEmployeeBase(EmployeeBase instance);
  partial void UpdateEmployeeBase(EmployeeBase instance);
  partial void DeleteEmployeeBase(EmployeeBase instance);
  #endregion
	
	public HR_LoginDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BASE_DATAConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HR_LoginDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HR_LoginDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HR_LoginDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HR_LoginDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<EmployeeBase> EmployeeBase
	{
		get
		{
			return this.GetTable<EmployeeBase>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeBase")]
public partial class EmployeeBase : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Creator;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _Modidate;
	
	private string _UserID;
	
	private string _PASSWORD;
	
	private string _UserName;
	
	private string _EMAIL;
	
	private string _ExtTelephone;
	
	private string _BU;
	
	private string _DEPARTMENT;
	
	private string _SignLevel;
	
	private string _NotesID;
	
	private string _Dept;
	
	private string _DeptLevel;
	
	private string _SuperiorID;
	
	private string _SuperiorName;
	
	private string _SuperiorNotesID;
	
	private string _FirstAgentNotesID;
	
	private string _SecondAgentNotesID;
	
	private string _ThirdAgentNotesID;
	
	private string _AgentTurnOn;
	
	private string _FlagOfLeft;
	
	private string _YearsOfInduction;
	
	private string _YearsOfOutside;
	
	private string _SalaryLevel;
	
	private string _InductionDate;
	
	private string _AllSuperiorNotesID;
	
	private string _SystemActive;
	
	private string _AssignPower;
	
	private System.Guid _rowguid;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModidateChanging(string value);
    partial void OnModidateChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnExtTelephoneChanging(string value);
    partial void OnExtTelephoneChanged();
    partial void OnBUChanging(string value);
    partial void OnBUChanged();
    partial void OnDEPARTMENTChanging(string value);
    partial void OnDEPARTMENTChanged();
    partial void OnSignLevelChanging(string value);
    partial void OnSignLevelChanged();
    partial void OnNotesIDChanging(string value);
    partial void OnNotesIDChanged();
    partial void OnDeptChanging(string value);
    partial void OnDeptChanged();
    partial void OnDeptLevelChanging(string value);
    partial void OnDeptLevelChanged();
    partial void OnSuperiorIDChanging(string value);
    partial void OnSuperiorIDChanged();
    partial void OnSuperiorNameChanging(string value);
    partial void OnSuperiorNameChanged();
    partial void OnSuperiorNotesIDChanging(string value);
    partial void OnSuperiorNotesIDChanged();
    partial void OnFirstAgentNotesIDChanging(string value);
    partial void OnFirstAgentNotesIDChanged();
    partial void OnSecondAgentNotesIDChanging(string value);
    partial void OnSecondAgentNotesIDChanged();
    partial void OnThirdAgentNotesIDChanging(string value);
    partial void OnThirdAgentNotesIDChanged();
    partial void OnAgentTurnOnChanging(string value);
    partial void OnAgentTurnOnChanged();
    partial void OnFlagOfLeftChanging(string value);
    partial void OnFlagOfLeftChanged();
    partial void OnYearsOfInductionChanging(string value);
    partial void OnYearsOfInductionChanged();
    partial void OnYearsOfOutsideChanging(string value);
    partial void OnYearsOfOutsideChanged();
    partial void OnSalaryLevelChanging(string value);
    partial void OnSalaryLevelChanged();
    partial void OnInductionDateChanging(string value);
    partial void OnInductionDateChanged();
    partial void OnAllSuperiorNotesIDChanging(string value);
    partial void OnAllSuperiorNotesIDChanged();
    partial void OnSystemActiveChanging(string value);
    partial void OnSystemActiveChanged();
    partial void OnAssignPowerChanging(string value);
    partial void OnAssignPowerChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
	
	public EmployeeBase()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(20)")]
	public string Creator
	{
		get
		{
			return this._Creator;
		}
		set
		{
			if ((this._Creator != value))
			{
				this.OnCreatorChanging(value);
				this.SendPropertyChanging();
				this._Creator = value;
				this.SendPropertyChanged("Creator");
				this.OnCreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(20)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(20)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modidate", DbType="VarChar(20)")]
	public string Modidate
	{
		get
		{
			return this._Modidate;
		}
		set
		{
			if ((this._Modidate != value))
			{
				this.OnModidateChanging(value);
				this.SendPropertyChanging();
				this._Modidate = value;
				this.SendPropertyChanged("Modidate");
				this.OnModidateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(30)")]
	public string PASSWORD
	{
		get
		{
			return this._PASSWORD;
		}
		set
		{
			if ((this._PASSWORD != value))
			{
				this.OnPASSWORDChanging(value);
				this.SendPropertyChanging();
				this._PASSWORD = value;
				this.SendPropertyChanged("PASSWORD");
				this.OnPASSWORDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(20)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
	public string EMAIL
	{
		get
		{
			return this._EMAIL;
		}
		set
		{
			if ((this._EMAIL != value))
			{
				this.OnEMAILChanging(value);
				this.SendPropertyChanging();
				this._EMAIL = value;
				this.SendPropertyChanged("EMAIL");
				this.OnEMAILChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtTelephone", DbType="VarChar(50)")]
	public string ExtTelephone
	{
		get
		{
			return this._ExtTelephone;
		}
		set
		{
			if ((this._ExtTelephone != value))
			{
				this.OnExtTelephoneChanging(value);
				this.SendPropertyChanging();
				this._ExtTelephone = value;
				this.SendPropertyChanged("ExtTelephone");
				this.OnExtTelephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(20)")]
	public string BU
	{
		get
		{
			return this._BU;
		}
		set
		{
			if ((this._BU != value))
			{
				this.OnBUChanging(value);
				this.SendPropertyChanging();
				this._BU = value;
				this.SendPropertyChanged("BU");
				this.OnBUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(10)")]
	public string DEPARTMENT
	{
		get
		{
			return this._DEPARTMENT;
		}
		set
		{
			if ((this._DEPARTMENT != value))
			{
				this.OnDEPARTMENTChanging(value);
				this.SendPropertyChanging();
				this._DEPARTMENT = value;
				this.SendPropertyChanged("DEPARTMENT");
				this.OnDEPARTMENTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignLevel", DbType="VarChar(10)")]
	public string SignLevel
	{
		get
		{
			return this._SignLevel;
		}
		set
		{
			if ((this._SignLevel != value))
			{
				this.OnSignLevelChanging(value);
				this.SendPropertyChanging();
				this._SignLevel = value;
				this.SendPropertyChanged("SignLevel");
				this.OnSignLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotesID", DbType="VarChar(30)")]
	public string NotesID
	{
		get
		{
			return this._NotesID;
		}
		set
		{
			if ((this._NotesID != value))
			{
				this.OnNotesIDChanging(value);
				this.SendPropertyChanging();
				this._NotesID = value;
				this.SendPropertyChanged("NotesID");
				this.OnNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="VarChar(50)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this.OnDeptChanging(value);
				this.SendPropertyChanging();
				this._Dept = value;
				this.SendPropertyChanged("Dept");
				this.OnDeptChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptLevel", DbType="VarChar(10)")]
	public string DeptLevel
	{
		get
		{
			return this._DeptLevel;
		}
		set
		{
			if ((this._DeptLevel != value))
			{
				this.OnDeptLevelChanging(value);
				this.SendPropertyChanging();
				this._DeptLevel = value;
				this.SendPropertyChanged("DeptLevel");
				this.OnDeptLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorID", DbType="VarChar(60)")]
	public string SuperiorID
	{
		get
		{
			return this._SuperiorID;
		}
		set
		{
			if ((this._SuperiorID != value))
			{
				this.OnSuperiorIDChanging(value);
				this.SendPropertyChanging();
				this._SuperiorID = value;
				this.SendPropertyChanged("SuperiorID");
				this.OnSuperiorIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorName", DbType="VarChar(60)")]
	public string SuperiorName
	{
		get
		{
			return this._SuperiorName;
		}
		set
		{
			if ((this._SuperiorName != value))
			{
				this.OnSuperiorNameChanging(value);
				this.SendPropertyChanging();
				this._SuperiorName = value;
				this.SendPropertyChanged("SuperiorName");
				this.OnSuperiorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperiorNotesID", DbType="VarChar(20)")]
	public string SuperiorNotesID
	{
		get
		{
			return this._SuperiorNotesID;
		}
		set
		{
			if ((this._SuperiorNotesID != value))
			{
				this.OnSuperiorNotesIDChanging(value);
				this.SendPropertyChanging();
				this._SuperiorNotesID = value;
				this.SendPropertyChanged("SuperiorNotesID");
				this.OnSuperiorNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstAgentNotesID", DbType="VarChar(20)")]
	public string FirstAgentNotesID
	{
		get
		{
			return this._FirstAgentNotesID;
		}
		set
		{
			if ((this._FirstAgentNotesID != value))
			{
				this.OnFirstAgentNotesIDChanging(value);
				this.SendPropertyChanging();
				this._FirstAgentNotesID = value;
				this.SendPropertyChanged("FirstAgentNotesID");
				this.OnFirstAgentNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondAgentNotesID", DbType="VarChar(20)")]
	public string SecondAgentNotesID
	{
		get
		{
			return this._SecondAgentNotesID;
		}
		set
		{
			if ((this._SecondAgentNotesID != value))
			{
				this.OnSecondAgentNotesIDChanging(value);
				this.SendPropertyChanging();
				this._SecondAgentNotesID = value;
				this.SendPropertyChanged("SecondAgentNotesID");
				this.OnSecondAgentNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdAgentNotesID", DbType="VarChar(20)")]
	public string ThirdAgentNotesID
	{
		get
		{
			return this._ThirdAgentNotesID;
		}
		set
		{
			if ((this._ThirdAgentNotesID != value))
			{
				this.OnThirdAgentNotesIDChanging(value);
				this.SendPropertyChanging();
				this._ThirdAgentNotesID = value;
				this.SendPropertyChanged("ThirdAgentNotesID");
				this.OnThirdAgentNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentTurnOn", DbType="VarChar(10)")]
	public string AgentTurnOn
	{
		get
		{
			return this._AgentTurnOn;
		}
		set
		{
			if ((this._AgentTurnOn != value))
			{
				this.OnAgentTurnOnChanging(value);
				this.SendPropertyChanging();
				this._AgentTurnOn = value;
				this.SendPropertyChanged("AgentTurnOn");
				this.OnAgentTurnOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagOfLeft", DbType="VarChar(10)")]
	public string FlagOfLeft
	{
		get
		{
			return this._FlagOfLeft;
		}
		set
		{
			if ((this._FlagOfLeft != value))
			{
				this.OnFlagOfLeftChanging(value);
				this.SendPropertyChanging();
				this._FlagOfLeft = value;
				this.SendPropertyChanged("FlagOfLeft");
				this.OnFlagOfLeftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsOfInduction", DbType="VarChar(20)")]
	public string YearsOfInduction
	{
		get
		{
			return this._YearsOfInduction;
		}
		set
		{
			if ((this._YearsOfInduction != value))
			{
				this.OnYearsOfInductionChanging(value);
				this.SendPropertyChanging();
				this._YearsOfInduction = value;
				this.SendPropertyChanged("YearsOfInduction");
				this.OnYearsOfInductionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsOfOutside", DbType="VarChar(20)")]
	public string YearsOfOutside
	{
		get
		{
			return this._YearsOfOutside;
		}
		set
		{
			if ((this._YearsOfOutside != value))
			{
				this.OnYearsOfOutsideChanging(value);
				this.SendPropertyChanging();
				this._YearsOfOutside = value;
				this.SendPropertyChanged("YearsOfOutside");
				this.OnYearsOfOutsideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryLevel", DbType="VarChar(20)")]
	public string SalaryLevel
	{
		get
		{
			return this._SalaryLevel;
		}
		set
		{
			if ((this._SalaryLevel != value))
			{
				this.OnSalaryLevelChanging(value);
				this.SendPropertyChanging();
				this._SalaryLevel = value;
				this.SendPropertyChanged("SalaryLevel");
				this.OnSalaryLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InductionDate", DbType="VarChar(20)")]
	public string InductionDate
	{
		get
		{
			return this._InductionDate;
		}
		set
		{
			if ((this._InductionDate != value))
			{
				this.OnInductionDateChanging(value);
				this.SendPropertyChanging();
				this._InductionDate = value;
				this.SendPropertyChanged("InductionDate");
				this.OnInductionDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllSuperiorNotesID", DbType="VarChar(30)")]
	public string AllSuperiorNotesID
	{
		get
		{
			return this._AllSuperiorNotesID;
		}
		set
		{
			if ((this._AllSuperiorNotesID != value))
			{
				this.OnAllSuperiorNotesIDChanging(value);
				this.SendPropertyChanging();
				this._AllSuperiorNotesID = value;
				this.SendPropertyChanged("AllSuperiorNotesID");
				this.OnAllSuperiorNotesIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemActive", DbType="VarChar(2)")]
	public string SystemActive
	{
		get
		{
			return this._SystemActive;
		}
		set
		{
			if ((this._SystemActive != value))
			{
				this.OnSystemActiveChanging(value);
				this.SendPropertyChanging();
				this._SystemActive = value;
				this.SendPropertyChanged("SystemActive");
				this.OnSystemActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignPower", DbType="VarChar(2)")]
	public string AssignPower
	{
		get
		{
			return this._AssignPower;
		}
		set
		{
			if ((this._AssignPower != value))
			{
				this.OnAssignPowerChanging(value);
				this.SendPropertyChanging();
				this._AssignPower = value;
				this.SendPropertyChanged("AssignPower");
				this.OnAssignPowerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid rowguid
	{
		get
		{
			return this._rowguid;
		}
		set
		{
			if ((this._rowguid != value))
			{
				this.OnrowguidChanging(value);
				this.SendPropertyChanging();
				this._rowguid = value;
				this.SendPropertyChanged("rowguid");
				this.OnrowguidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
